/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴、God_Dragon
 @version : V0.7.0 - 2020-12-27
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    //地图名称
    'Kanto': '关东地区',
    'Johto': '城都地区',
    'Hoenn': '丰缘地区',
    'Sinnoh': '神奥地区',
    'Unova': '合众地区',
    //1.0.宝可梦
    'Bulbasaur': '妙蛙种子',
    'Ivysaur': '妙蛙草',
    'Venusaur': '妙蛙花',
    'Charmander': '小火龙',
    'Charmeleon': '火恐龙',
    'Charizard': '喷火龙',
    'Squirtle': '杰尼龟',
    'Wartortle': '卡咪龟',
    'Blastoise': '水箭龟',
    'Caterpie': '绿毛虫',
    'Metapod': '铁甲蛹',
    'Butterfree': '巴大蝶',
    'Weedle': '独角虫',
    'Kakuna': '铁壳蛹',
    'Beedrill': '大针蜂',
    'Pidgey': '波波',
    'Pidgeotto': '比比鸟',
    'Pidgeot': '大比鸟',
    'Rattata': '小拉达',
    'Raticate': '拉达',
    'Spearow': '烈雀',
    'Fearow': '大嘴雀',
    'Ekans': '阿柏蛇',
    'Arbok': '阿柏怪',
    'Pikachu': '皮卡丘',
    'Raichu': '雷丘',
    'Sandshrew': '穿山鼠',
    'Sandslash': '穿山王',
    'Nidoran(F)': '尼多兰',
    'Nidorina': '尼多娜',
    'Nidoqueen': '尼多后',
    'Nidoran(M)': '尼多朗',
    'Nidorino': '尼多力诺',
    'Nidoking': '尼多王',
    'Clefairy': '皮皮',
    'Clefable': '皮可西',
    'Vulpix': '六尾',
    'Ninetales': '九尾',
    'Jigglypuff': '胖丁',
    'Wigglytuff': '胖可丁',
    'Zubat': '超音蝠',
    'Golbat': '大嘴蝠',
    'Oddish': '走路草',
    'Gloom': '臭臭花',
    'Vileplume': '霸王花',
    'Paras': '派拉斯',
    'Parasect': '派拉斯特',
    'Venonat': '毛球',
    'Venomoth': '摩鲁蛾',
    'Diglett': '地鼠',
    'Dugtrio': '三地鼠',
    'Meowth': '喵喵',
    'Persian': '猫老大',
    'Psyduck': '可达鸭',
    'Golduck': '哥达鸭',
    'Mankey': '猴怪',
    'Primeape': '火暴猴',
    'Growlithe': '卡蒂狗',
    'Arcanine': '风速狗',
    'Poliwag': '蚊香蝌蚪',
    'Poliwhirl': '蚊香君',
    'Poliwrath': '蚊香泳士',
    'Abra': '凯西',
    'Kadabra': '勇基拉',
    'Alakazam': '胡地',
    'Machop': '腕力',
    'Machoke': '豪力',
    'Machamp': '怪力',
    'Bellsprout': '喇叭芽',
    'Weepinbell': '口呆花',
    'Victreebel': '大食花',
    'Tentacool': '玛瑙水母',
    'Tentacruel': '毒刺水母',
    'Geodude': '小拳石',
    'Graveler': '隆隆石',
    'Golem': '隆隆岩',
    'Ponyta': '小火马',
    'Rapidash': '烈焰马',
    'Slowpoke': '呆呆兽',
    'Slowbro': '呆壳兽',
    'Magnemite': '小磁怪',
    'Magneton': '三合一磁怪',
    'Farfetch\'d': '大葱鸭',
    'Doduo': '嘟嘟',
    'Dodrio': '嘟嘟利',
    'Seel': '小海狮',
    'Dewgong': '白海狮',
    'Grimer': '臭泥',
    'Muk': '臭臭泥',
    'Shellder': '大舌贝',
    'Cloyster': '刺甲贝',
    'Gastly': '鬼斯',
    'Haunter': '鬼斯通',
    'Gengar': '耿鬼',
    'Onix': '大岩蛇',
    'Drowzee': '催眠貘',
    'Hypno': '引梦貘人',
    'Krabby': '大钳蟹',
    'Kingler': '巨钳蟹',
    'Voltorb': '霹雳电球',
    'Electrode': '顽皮雷弹',
    'Exeggcute': '蛋蛋',
    'Exeggutor': '椰蛋树',
    'Cubone': '卡拉卡拉',
    'Marowak': '嘎啦嘎啦',
    'Hitmonlee': '飞腿郎',
    'Hitmonchan': '快拳郎',
    'Lickitung': '大舌头',
    'Koffing': '瓦斯弹',
    'Weezing': '双弹瓦斯',
    'Rhyhorn': '独角犀牛',
    'Rhydon': '钻角犀兽',
    'Chansey': '吉利蛋',
    'Tangela': '蔓藤怪',
    'Kangaskhan': '袋兽',
    'Horsea': '墨海马',
    'Seadra': '海刺龙',
    'Goldeen': '角金鱼',
    'Seaking': '金鱼王',
    'Staryu': '海星星',
    'Starmie': '宝石海星',
    'Mr. Mime': '魔墙人偶',
    'Scyther': '飞天螳螂',
    'Jynx': '迷唇姐',
    'Electabuzz': '电击兽',
    'Magmar': '鸭嘴火兽',
    'Pinsir': '凯罗斯',
    'Tauros': '肯泰罗',
    'Magikarp': '鲤鱼王',
    'Gyarados': '暴鲤龙',
    'Lapras': '拉普拉斯',
    'Ditto': '百变怪',
    'Eevee': '伊布',
    'Vaporeon': '水伊布',
    'Jolteon': '雷伊布',
    'Flareon': '火伊布',
    'Porygon': '多边兽',
    'Omanyte': '菊石兽',
    'Omastar': '多刺菊石兽',
    'Kabuto': '化石盔',
    'Kabutops': '镰刀盔',
    'Aerodactyl': '化石翼龙',
    'Snorlax': '卡比兽',
    'Dratini': '迷你龙',
    'Dragonair': '哈克龙',
    'Dragonite': '快龙',
    'Articuno': '急冻鸟',
    'Zapdos': '闪电鸟',
    'Moltres': '火焰鸟',
    'Mewtwo': '超梦',
    'Mew': '梦幻',
    //城都地区
    'Chikorita': '菊草叶',
    'Bayleef': '月桂叶',
    'Meganium': '大竺葵',
    'Cyndaquil': '火球鼠',
    'Quilava': '火岩鼠',
    'Typhlosion': '火暴兽',
    'Totodile': '小锯鳄',
    'Croconaw': '蓝鳄',
    'Feraligatr': '大力鳄',
    'Sentret': '尾立',
    'Furret': '大尾立',
    'Hoothoot': '咕咕',
    'Noctowl': '猫头夜鹰',
    'Ledyba': '芭瓢虫',
    'Ledian': '安瓢虫',
    'Spinarak': '圆丝蛛',
    'Ariados': '阿利多斯',
    'Crobat': '叉字蝠',
    'Chinchou': '灯笼鱼',
    'Lanturn': '电灯怪',
    'Pichu': '皮丘',
    'Cleffa': '皮宝宝',
    'Igglybuff': '宝宝丁',
    'Togepi': '波克比',
    'Togetic': '波克基古',
    'Natu': '天然雀',
    'Xatu': '天然鸟',
    'Mareep': '咩利羊',
    'Flaaffy': '茸茸羊',
    'Ampharos': '电龙',
    'Bellossom': '美丽花',
    'Marill': '玛力露',
    'Azumarill': '玛力露丽',
    'Sudowoodo': '树才怪',
    'Politoed': '蚊香蛙皇',
    'Hoppip': '毽子草',
    'Skiploom': '毽子花',
    'Jumpluff': '毽子棉',
    'Aipom': '长尾怪手',
    'Sunkern': '向日种子',
    'Sunflora': '向日花怪',
    'Yanma': '蜻蜻蜓',
    'Wooper': '乌波',
    'Quagsire': '沼王',
    'Espeon': '太阳伊布',
    'Umbreon': '月亮伊布',
    'Murkrow': '黑暗鸦',
    'Slowking': '呆呆王',
    'Misdreavus': '梦妖',
    'Unown': '未知图腾',
    'Wobbuffet': '果然翁',
    'Girafarig': '麒麟奇',
    'Pineco': '榛果球',
    'Forretress': '佛烈托斯',
    'Dunsparce': '土龙弟弟',
    'Gligar': '天蝎',
    'Steelix': '大钢蛇',
    'Snubbull': '布鲁',
    'Granbull': '布鲁皇',
    'Qwilfish': '千针鱼',
    'Scizor': '巨钳螳螂',
    'Shuckle': '壶壶',
    'Heracross': '赫拉克罗斯',
    'Sneasel': '狃拉',
    'Teddiursa': '熊宝宝',
    'Ursaring': '圈圈熊',
    'Slugma': '熔岩虫',
    'Magcargo': '熔岩蜗牛',
    'Swinub': '小山猪',
    'Piloswine': '长毛猪',
    'Corsola': '太阳珊瑚',
    'Remoraid': '铁炮鱼',
    'Octillery': '章鱼桶',
    'Delibird': '信使鸟',
    'Mantine': '巨翅飞鱼',
    'Skarmory': '盔甲鸟',
    'Houndour': '戴鲁比',
    'Houndoom': '黑鲁加',
    'Kingdra': '刺龙王',
    'Phanpy': '小小象',
    'Donphan': '顿甲',
    'Porygon2': '多边兽Ⅱ',
    'Stantler': '惊角鹿',
    'Smeargle': '图图犬',
    'Tyrogue': '无畏小子',
    'Hitmontop': '战舞郎',
    'Smoochum': '迷唇娃',
    'Elekid': '电击怪',
    'Magby': '鸭嘴宝宝',
    'Miltank': '大奶罐',
    'Blissey': '幸福蛋',
    'Raikou': '雷公',
    'Entei': '炎帝',
    'Suicune': '水君',
    'Larvitar': '幼基拉斯',
    'Pupitar': '沙基拉斯',
    'Tyranitar': '班基拉斯',
    'Lugia': '洛奇亚',
    'Ho-Oh': '凤王',
    'Celebi': '雪拉比',
    //丰缘地区
    'Treecko': '木守宫',
    'Grovyle': '森林蜥蜴',
    'Sceptile': '蜥蜴王',
    'Torchic': '火稚鸡',
    'Combusken': '力壮鸡',
    'Blaziken': '火焰鸡',
    'Mudkip': '水跃鱼',
    //258
    'Marshtomp': '沼跃鱼',
    'Swampert': '巨沼怪',
    'Poochyena': '土狼犬',
    'Mightyena': '大狼犬',
    'Zigzagoon': '蛇纹熊',
    'Linoone': '直冲熊',
    'Wurmple': '刺尾虫',
    'Silcoon': '甲壳茧',
    'Beautifly': '狩猎凤蝶',
    'Cascoon': '盾甲茧',
    'Dustox': '毒粉蛾',
    'Lotad': '莲叶童子',
    'Lombre': '莲帽小童',
    'Ludicolo': '乐天河童',
    'Seedot': '橡实果',
    'Nuzleaf': '长鼻叶',
    'Shiftry': '狡猾天狗',
    'Taillow': '傲骨燕',
    'Swellow': '大王燕',
    'Wingull': '长翅鸥',
    'Pelipper': '大嘴鸥',
    'Ralts': '拉鲁拉丝',
    'Kirlia': '奇鲁莉安',
    'Gardevoir': '沙奈朵',
    'Surskit': '溜溜糖球',
    'Masquerain': '雨翅蛾',
    'Shroomish': '蘑蘑菇',
    'Breloom': '斗笠菇',
    'Slakoth': '懒人獭',
    'Vigoroth': '过动猿',
    'Slaking': '请假王',
    'Nincada': '土居忍士',
    'Ninjask': '铁面忍者',
    'Shedinja': '脱壳忍者',
    'Whismur': '咕妞妞',
    'Loudred': '吼爆弹',
    'Exploud': '爆音怪',
    'Makuhita': '幕下力士',
    'Hariyama': '铁掌力士',
    'Azurill': '露力丽',
    'Nosepass': '朝北鼻',
    'Skitty': '向尾喵',
    //300
    'Delcatty': '优雅猫',
    'Sableye': '勾魂眼',
    'Mawile': '大嘴娃',
    'Aron': '可可多拉',
    'Lairon': '可多拉',
    'Aggron': '波士可多拉',
    'Meditite': '玛沙那',
    'Medicham': '恰雷姆',
    'Electrike': '落雷兽',
    'Manectric': '雷电兽',
    'Plusle': '正电拍拍',
    'Minun': '负电拍拍',
    'Volbeat': '电萤虫',
    'Illumise': '甜甜萤',
    'Roselia': '毒蔷薇',
    'Gulpin': '溶食兽',
    'Swalot': '吞食兽',
    'Carvanha': '利牙鱼',
    'Sharpedo': '巨牙鲨',
    'Wailmer': '吼吼鲸',
    'Wailord': '吼鲸王',
    'Numel': '呆火驼',
    'Camerupt': '喷火驼',
    'Torkoal': '煤炭龟',
    'Spoink': '跳跳猪',
    'Grumpig': '噗噗猪',
    'Spinda': '晃晃斑',
    'Trapinch': '大颚蚁',
    'Vibrava': '超音波幼虫',
    'Flygon': '沙漠蜻蜓',
    'Cacnea': '刺球仙人掌',
    'Cacturne': '梦歌仙人掌',
    'Swablu': '青绵鸟',
    'Altaria': '七夕青鸟',
    'Zangoose': '猫鼬斩',
    'Seviper': '饭匙蛇',
    'Lunatone': '月石',
    'Solrock': '太阳岩',
    'Barboach': '泥泥鳅',
    'Whiscash': '鲶鱼王',
    'Corphish': '龙虾小兵',
    'Crawdaunt': '铁螯龙虾',
    'Baltoy': '天秤偶',
    'Claydol': '念力土偶',
    'Lileep': '触手百合',
    'Cradily': '摇篮百合',
    'Anorith': '太古羽虫',
    'Armaldo': '太古盔甲',
    'Feebas': '丑丑鱼',
    'Milotic': '美纳斯',
    'Castform': '飘浮泡泡',
    'Kecleon': '变隐龙',
    'Shuppet': '怨影娃娃',
    'Banette': '诅咒娃娃',
    'Duskull': '夜巡灵',
    'Dusclops': '彷徨夜灵',
    'Tropius': '热带龙',
    'Chimecho': '风铃铃',
    'Absol': '阿勃梭鲁',
    'Wynaut': '小果然',
    'Snorunt': '雪童子',
    'Glalie': '冰鬼护',
    'Spheal': '海豹球',
    'Sealeo': '海魔狮',
    'Walrein': '帝牙海狮',
    'Clamperl': '珍珠贝',
    'Huntail': '猎斑鱼',
    'Gorebyss': '樱花鱼',
    'Relicanth': '古空棘鱼',
    'Luvdisc': '爱心鱼',
    'Bagon': '宝贝龙',
    'Shelgon': '甲壳龙',
    'Salamence': '暴飞龙',
    'Beldum': '铁哑铃',
    'Metang': '金属怪',
    'Metagross': '巨金怪',
    'Regirock': '雷吉洛克',
    'Regice': '雷吉艾斯',
    'Registeel': '雷吉斯奇鲁',
    'Latias': '拉帝亚斯',
    'Latios': '拉帝欧斯',
    'Kyogre': '盖欧卡',
    'Groudon': '固拉多',
    'Rayquaza': '烈空坐',
    'Jirachi': '基拉祈',
    'Deoxys': '代欧奇希斯',
    //神奥地区
    'Turtwig': '草苗龟',
    'Grotle': '树林龟',
    'Torterra': '土台龟',
    'Chimchar': '小火焰猴',
    'Monferno': '猛火猴',
    'Infernape': '烈焰猴',
    'Piplup': '波加曼',
    'Prinplup': '波皇子',
    'Empoleon': '帝王拿波',
    'Starly': '姆克儿',
    'Staravia': '姆克鸟',
    'Staraptor': '姆克鹰',
    'Bidoof': '大牙狸',
    //400
    'Bibarel': '大尾狸',
    'Kricketot': '圆法师',
    'Kricketune': '音箱蟀',
    'Shinx': '小猫怪',
    'Luxio': '勒克猫',
    'Luxray': '伦琴猫',
    'Budew': '含羞苞',
    'Roserade': '罗丝雷朵',
    'Cranidos': '头盖龙',
    'Rampardos': '战槌龙',
    'Shieldon': '盾甲龙',
    'Bastiodon': '护城龙',
    'Burmy': '结草儿',
    'Wormadam': '结草贵妇',
    'Mothim': '绅士蛾',
    'Combee': '三蜜蜂',
    'Vespiquen': '蜂女王',
    'Pachirisu': '帕奇利兹',
    'Buizel': '泳圈鼬',
    'Floatzel': '浮潜鼬',
    'Cherubi': '樱花宝',
    'Cherrim': '樱花儿',
    'Shellos': '无壳海兔',
    'Gastrodon': '海兔兽',
    'Ambipom': '双尾怪手',
    'Drifloon': '飘飘球',
    'Drifblim': '随风球',
    'Buneary': '卷卷耳',
    'Lopunny': '长耳兔',
    'Mismagius': '梦妖魔',
    'Honchkrow': '乌鸦头头',
    'Glameow': '魅力喵',
    'Purugly': '东施喵',
    'Chingling': '铃铛响',
    'Stunky': '臭鼬噗',
    'Skuntank': '坦克臭鼬',
    'Bronzor': '铜镜怪',
    'Bronzong': '青铜钟',
    'Bonsly': '盆才怪',
    'Mime Jr.': '魔尼尼',
    'Happiny': '小福蛋',
    'Chatot': '聒噪鸟',
    'Spiritomb': '花岩怪',
    'Gible': '圆陆鲨',
    'Gabite': '尖牙陆鲨',
    'Garchomp': '烈咬陆鲨',
    'Munchlax': '小卡比兽',
    'Riolu': '利欧路',
    'Lucario': '路卡利欧',
    'Hippopotas': '沙河马',
    'Hippowdon': '河马兽',
    'Skorupi': '钳尾蝎',
    'Drapion': '龙王蝎',
    'Croagunk': '不良蛙',
    'Toxicroak': '毒骷蛙',
    'Carnivine': '尖牙笼',
    'Finneon': '荧光鱼',
    'Lumineon': '霓虹鱼',
    'Mantyke': '小球飞鱼',
    'Snover': '雪笠怪',
    'Abomasnow': '暴雪王',
    'Weavile': '玛狃拉',
    'Magnezone': '自爆磁怪',
    'Lickilicky': '大舌舔',
    'Rhyperior': '超甲狂犀',
    'Tangrowth': '巨蔓藤',
    'Electivire': '电击魔兽',
    'Magmortar': '鸭嘴炎兽',
    'Togekiss': '波克基斯',
    'Yanmega': '远古巨蜓',
    'Leafeon': '叶伊布',
    'Glaceon': '冰伊布',
    'Gliscor': '天蝎王',
    'Mamoswine': '象牙猪',
    'Porygon-Z': '多边兽Ｚ',
    'Gallade': '艾路雷朵',
    'Probopass': '大朝北鼻',
    'Dusknoir': '黑夜魔灵',
    'Froslass': '雪妖女',
    'Rotom': '洛托姆',
    'Uxie': '由克希',
    'Mesprit': '艾姆利多',
    'Azelf': '亚克诺姆',
    'Dialga': '帝牙卢卡',
    'Palkia': '帕路奇亚',
    'Heatran': '席多蓝恩',
    'Regigigas': '雷吉奇卡斯',
    'Giratina': '骑拉帝纳',
    'Cresselia': '克雷色利亚',
    'Phione': '霏欧纳',
    'Manaphy': '玛纳霏',
    'Darkrai': '达克莱伊',
    'Shaymin': '谢米',
    'Arceus': '阿尔宙斯',
    'Victini': '比克提尼',
    //合众地区
    'Snivy': '藤藤蛇',
    'Servine': '青藤蛇',
    'Serperior': '君主蛇',
    'Tepig': '暖暖猪',
    'Pignite': '炒炒猪',
    'Emboar': '炎武王',
    //500
    'Oshawott': '水水獭',
    'Dewott': '双刃丸',
    'Samurott': '大剑鬼',
    'Patrat': '探探鼠',
    'Watchog': '步哨鼠',
    'Lillipup': '小约克',
    'Herdier': '哈约克',
    'Stoutland': '长毛狗',
    'Purrloin': '扒手猫',
    'Liepard': '酷豹',
    'Pansage': '花椰猴',
    'Simisage': '花椰猿',
    'Pansear': '爆香猴',
    'Simisear': '爆香猿',
    'Panpour': '冷水猴',
    'Simipour': '冷水猿',
    'Munna': '食梦梦',
    'Musharna': '梦梦蚀',
    'Pidove': '豆豆鸽',
    'Tranquill': '咕咕鸽',
    'Unfezant': '高傲雉鸡',
    'Blitzle': '斑斑马',
    'Zebstrika': '雷电斑马',
    'Roggenrola': '石丸子',
    'Boldore': '地幔岩',
    'Gigalith': '庞岩怪',
    'Woobat': '滚滚蝙蝠',
    'Swoobat': '心蝙蝠',
    'Drilbur': '螺钉地鼠',
    'Excadrill': '龙头地鼠',
    'Audino': '差不多娃娃',
    'Timburr': '搬运小匠',
    'Gurdurr': '铁骨土人',
    'Conkeldurr': '修建老匠',
    'Tympole': '圆蝌蚪',
    'Palpitoad': '蓝蟾蜍',
    'Seismitoad': '蟾蜍王',
    'Throh': '投摔鬼',
    'Sawk': '打击鬼',
    'Sewaddle': '虫宝包',
    'Swadloon': '宝包茧',
    'Leavanny': '保姆虫',
    'Venipede': '百足蜈蚣',
    'Whirlipede': '车轮球',
    'Scolipede': '蜈蚣王',
    'Cottonee': '木棉球',
    'Whimsicott': '风妖精',
    'Petilil': '百合根娃娃',
    'Lilligant': '裙儿小姐',
    'Basculin': '野蛮鲈鱼',
    'Sandile': '黑眼鳄',
    'Krokorok': '混混鳄',
    'Krookodile': '流氓鳄',
    'Darumaka': '火红不倒翁',
    'Darmanitan': '达摩狒狒',
    'Maractus': '沙铃仙人掌',
    'Dwebble': '石居蟹',
    'Crustle': '岩殿居蟹',
    'Scraggy': '滑滑小子',
    'Scrafty': '头巾混混',
    'Sigilyph': '象征鸟',
    'Yamask': '哭哭面具',
    'Cofagrigus': '死神棺',
    'Tirtouga': '原盖海龟',
    'Carracosta': '肋骨海龟',
    'Archen': '始祖小鸟',
    'Archeops': '始祖大鸟',
    'Trubbish': '破破袋',
    'Garbodor': '灰尘山',
    'Zorua': '索罗亚',
    'Zoroark': '索罗亚克',
    'Minccino': '泡沫栗鼠',
    'Cinccino': '奇诺栗鼠',
    'Gothita': '哥德宝宝',
    'Gothorita': '哥德小童',
    'Gothitelle': '哥德小姐',
    'Solosis': '单卵细胞球',
    'Duosion': '双卵细胞球',
    'Reuniclus': '人造细胞卵',
    'Ducklett': '鸭宝宝',
    'Swanna': '舞天鹅',
    'Vanillite': '迷你冰',
    'Vanillish': '多多冰',
    'Vanilluxe': '双倍多多冰',
    'Deerling': '四季鹿',
    'Sawsbuck': '萌芽鹿',
    'Emolga': '电飞鼠',
    'Karrablast': '盖盖虫',
    'Escavalier': '骑士蜗牛',
    'Foongus': '哎呀球菇',
    'Amoonguss': '败露球菇',
    'Frillish': '轻飘飘',
    'Jellicent': '胖嘟嘟',
    'Alomomola': '保姆曼波',
    'Joltik': '电电虫',
    'Galvantula': '电蜘蛛',
    'Ferroseed': '种子铁球',
    'Ferrothorn': '坚果哑铃',
    'Klink': '齿轮儿',
    'Klang': '齿轮组',
    'Klinklang': '齿轮怪',
    'Tynamo': '麻麻小鱼',
    'Eelektrik': '麻麻鳗',
    'Eelektross': '麻麻鳗鱼王',
    'Elgyem': '小灰怪',
    'Beheeyem': '大宇怪',
    'Litwick': '烛光灵',
    'Lampent': '灯火幽灵',
    'Chandelure': '水晶灯火灵	',
    'Axew': '牙牙',
    'Fraxure': '斧牙龙',
    'Haxorus': '双斧战龙',
    'Cubchoo': '喷嚏熊',
    'Beartic': '冻原熊',
    'Cryogonal': '几何雪花',
    'Shelmet': '小嘴蜗',
    'Accelgor': '敏捷虫',
    'Stunfisk': '泥巴鱼',
    'Mienfoo': '功夫鼬',
    'Mienshao': '师父鼬',
    'Druddigon': '赤面龙',
    'Golett': '泥偶小人',
    'Golurk': '泥偶巨人',
    'Pawniard': '驹刀小兵',
    'Bisharp': '劈斩司令',
    'Bouffalant': '爆炸头水牛',
    'Rufflet': '毛头小鹰',
    'Braviary': '勇士雄鹰',
    'Vullaby': '秃鹰丫头',
    'Mandibuzz': '秃鹰娜',
    'Heatmor': '熔蚁兽',
    'Durant': '铁蚁',
    'Deino': '单首龙',
    'Zweilous': '双首暴龙',
    'Hydreigon': '三首恶龙',
    'Larvesta': '燃烧虫',
    'Volcarona': '火神蛾',
    'Cobalion': '勾帕路翁',
    'Terrakion': '代拉基翁',
    'Virizion': '毕力吉翁',
    'Tornadus': '龙卷云',
    'Thundurus': '雷电云',
    'Reshiram': '莱希拉姆',
    'Zekrom': '捷克罗姆',
    'Landorus': '土地云',
    'Kyurem': '酋雷姆',
    'Keldeo': '凯路迪欧',
    'Meloetta': '美洛耶塔',
    'Genesect': '盖诺赛克特',
    'Chespin': '哈力栗',
    //650
    'Chespin': '哈力栗',
    'Quilladin': '胖胖哈力',
    'Chesnaught': '布里卡隆',
    'Fennekin': '火狐狸',
    'Braixen': '长尾火狐',
    'Delphox': '妖火红狐',
    'Froakie': '呱呱泡蛙',
    'Frogadier': '呱头蛙',
    'Greninja': '甲贺忍蛙',
    'Bunnelby': '掘掘兔',
    'Diggersby': '掘地兔',
    'Fletchling': '小箭雀',
    'Fletchinder': '火箭雀',
    'Talonflame': '烈箭鹰',
    'Scatterbug': '粉蝶虫',
    'Spewpa': '粉蝶蛹',
    'Vivillon': '彩粉蝶',
    'Litleo': '小狮狮',
    'Pyroar': '火炎狮',
    'Flabebe': '花蓓蓓',
    'Floette': '花叶蒂',
    'Florges': '花洁夫人',
    'Skiddo': '坐骑小羊',
    'Gogoat': '坐骑山羊',
    'Pancham': '顽皮熊猫',
    'Pangoro': '流氓熊猫',
    'Furfrou': '多丽米亚',
    'Espurr': '妙喵',
    'Meowstic': '超能妙喵',
    'Honedge': '独剑鞘',
    'Doublade': '双剑鞘',
    'Aegislash': '坚盾剑怪',
    'Spritzee': '粉香香',
    'Aromatisse': '芳香精',
    'Swirlix': '绵绵泡芙',
    'Slurpuff': '胖甜妮',
    'Inkay': '好啦鱿',
    'Malamar': '乌贼王',
    'Binacle': '龟脚脚',
    'Barbaracle': '龟足巨铠',
    'Skrelp': '垃垃藻',
    'Dragalge': '毒藻龙',
    'Clauncher': '铁臂枪虾',
    'Clawitzer': '钢炮臂虾',
    'Helioptile': '伞电蜥',
    'Heliolisk': '光电伞蜥',
    'Tyrunt': '宝宝暴龙',
    'Tyrantrum': '怪颚龙',
    'Amaura': '冰雪龙',
    'Aurorus': '冰雪巨龙',
    'Sylveon': '仙子伊布',
    'Hawlucha': '摔角鹰人',
    'Dedenne': '咚咚鼠',
    'Carbink': '小碎钻',
    'Goomy': '黏黏宝',
    'Sliggoo': '黏美儿',
    'Goodra': '黏美龙',
    'Klefki': '钥圈儿',
    'Phantump': '小木灵',
    'Trevenant': '朽木妖',
    'Pumpkaboo': '南瓜精',
    'Gourgeist': '南瓜怪人',
    'Bergmite': '冰宝',
    'Avalugg': '冰岩怪',
    'Noibat': '嗡蝠',
    'Noivern': '音波龙',
    'Xerneas': '哲尔尼亚斯',
    'Yveltal': '伊裴尔塔尔',
    'Zygarde': '基格尔德',
    'Diancie': '蒂安希',
    'Hoopa': '胡帕',
    'Volcanion': '波尔凯尼恩',
    //阿罗拉地区
    'Rowlet': '木木枭',
    //722
    'Dartrix': '投羽枭',
    'Decidueye': '狙射树枭',
    'Litten': '火斑喵',
    'Torracat': '炎热喵',
    'Incineroar': '炽焰咆哮虎',
    'Popplio': '球球海狮',
    'Brionne': '花漾海狮',
    'Primarina': '西狮海壬',
    'Pikipek': '小笃儿',
    'Trumbeak': '喇叭啄鸟',
    'Toucannon': '铳嘴大鸟',
    'Yungoos': '猫鼬少',
    'Gumshoos': '猫鼬探长',
    'Grubbin': '强颚鸡母虫',
    'Charjabug': '虫电宝',
    'Vikavolt': '锹农炮虫',
    'Crabrawler': '好胜蟹',
    'Crabominable': '好胜毛蟹',
    'Oricorio': '花舞鸟',
    'Cutiefly': '萌虻',
    'Ribombee': '蝶结萌虻',
    'Rockruff': '岩狗狗',
    'Lycanroc': '鬃岩狼人',
    'Wishiwashi': '弱丁鱼',
    'Mareanie': '好坏星',
    'Toxapex': '超坏星',
    'Mudbray': '泥驴仔',
    'Mudsdale': '重泥挽马',
    'Dewpider': '滴蛛',
    'Araquanid': '滴蛛霸',
    'Fomantis': '伪螳草',
    'Lurantis': '兰螳花',
    'Morelull': '睡睡菇',
    'Shiinotic': '灯罩夜菇',
    'Salandit': '夜盗火蜥',
    'Salazzle': '焰后蜥',
    'Stufful': '童偶熊',
    'Bewear': '穿着熊',
    'Bounsweet': '甜竹竹',
    'Steenee': '甜舞妮',
    'Tsareena': '甜冷美后',
    'Comfey': '花疗环环',
    'Oranguru': '智挥猩',
    'Passimian': '投掷猴',
    'Wimpod': '胆小虫',
    'Golisopod': '具甲武者',
    'Sandygast': '沙丘娃',
    'Palossand': '噬沙堡爷',
    'Pyukumuku': '拳海参',
    'Type: Null': '属性：空',
    'Silvally': '银伴战兽',
    'Minior': '小陨星',
    'Komala': '树枕尾熊',
    'Turtonator': '爆焰龟兽',
    'Togedemaru': '托戈德玛尔',
    'Mimikyu': '谜拟Ｑ',
    'Bruxish': '磨牙彩皮鱼',
    'Drampa': '老翁龙',
    'Dhelmise': '破破舵轮',
    'Jangmo-o': '心鳞宝',
    'Hakamo-o': '鳞甲龙',
    'Kommo-o': '杖尾鳞甲龙',
    'Tapu Koko': '卡璞・鸣鸣',
    'Tapu Lele': '卡璞・蝶蝶',
    'Tapu Bulu': '卡璞・哞哞',
    'Tapu Fini': '卡璞・鳍鳍',
    'Cosmog': '科斯莫古',
    'Cosmoem': '科斯莫姆',
    'Solgaleo': '索尔迦雷欧',
    'Lunala': '露奈雅拉',
    'Nihilego': '虚吾伊德',
    'Buzzwole': '爆肌蚊',
    'Pheromosa': '费洛美螂',
    'Xurkitree': '电束木',
    'Celesteela': '铁火辉夜',
    'Kartana': '纸御剑',
    'Guzzlord': '恶食大王',
    'Necrozma': '奈克洛兹玛',
    'Magearna': '玛机雅娜',
    'Marshadow': '玛夏多',
    'Poipole': '毒贝比',
    'Naganadel': '四颚针龙',
    'Stakataka': '垒磊石',
    'Blacephalon': '砰头小丑',
    'Zeraora': '捷拉奥拉',
    //807
    //808开始
    'Meltan': '美录坦',
    'M-Venusaur': 'M-妙蛙花',
    'M-Charizard X': 'M-喷火龙 X',
    'M-Charizard Y': 'M-喷火龙 Y',
    'M-Blastoise': 'M-水箭龟',
    'M-Beedrill': 'M-大针蜂',
    'M-Pidgeot': 'M-大比鸟',
    'A-Rattata': 'A-小拉达',
    'A-Raticate': 'A-拉达',
    'A-Raichu': 'A-雷丘',
    'A-Sandshrew': 'A-穿山鼠',
    'A-Sandslash': 'A-穿山王',
    'A-Vulpix': 'A-六尾',
    'A-Ninetales': 'A-九尾',
    'A-Diglett': 'A-地鼠',
    'A-Dugtrio': 'A-三地鼠',
    'A-Meowth': 'A-喵喵',
    'A-Persian': 'A-猫老大',
    'M-Alakazam': 'M-胡地',
    'A-Geodude': 'A-小拳石',
    'A-Graveler': 'A-隆隆石',
    'A-Golem': 'A-隆隆岩',
    'M-Slowbro': 'M-呆壳兽',
    'A-Grimer': 'A-臭泥',
    'A-Muk': 'A-臭臭泥',
    'M-Gengar': 'M-耿鬼',
    'A-Exeggutor': 'A-椰蛋树',
    'A-Marowak': 'A-嘎啦嘎啦',
    'M-Kangaskhan': 'M-袋兽',
    'M-Pinsir': 'M-凯罗斯',
    'M-Gyarados': 'M-暴鲤龙',
    'M-Aerodactyl': 'M-化石翼龙',
    'M-Mewtwo X': 'M-超梦 X',
    'M-Mewtwo Y': 'M-超梦 Y',
    'M-Ampharos': 'M-电龙',
    'M-Steelix': 'M-大钢蛇',
    'M-Scizor': 'M-巨钳螳螂',
    'M-Heracross': 'M-赫拉克罗斯',
    'M-Houndoom': 'M-黑鲁加',
    'M-Tyranitar': 'M-班基拉斯',
    'M-Sceptile': 'M-蜥蜴王',
    'M-Blaziken': 'M-火焰鸡',
    'M-Swampert': 'M-巨沼怪',
    'M-Gardevoir': 'M-沙奈朵',
    'M-Sableye': 'M-勾魂眼',
    'M-Mawile': 'M-大嘴娃',
    'M-Aggron': 'M-波士可多拉',
    'M-Medicham': 'M-恰雷姆',
    'M-Manectric': 'M-雷电兽',
    'M-Sharpedo': 'M-巨牙鲨',
    'M-Camerupt': 'M-喷火驼',
    'M-Altaria': 'M-七夕青鸟',
    'M-Banette': 'M-诅咒娃娃',
    'M-Absol': 'M-阿勃梭鲁',
    'M-Glalie': 'M-冰鬼护',
    'M-Salamence': 'M-暴飞龙',
    'M-Metagross': 'M-巨金怪',
    'M-Latias': 'M-拉帝亚斯',
    'M-Latios': 'M-拉帝欧斯',
    //867开始
    'P-Kyogre': '原始盖欧卡',
    'P-Groudon': '原始古拉顿',
    'M-Rayquaza': 'M-裂空座',
    'Deoxys-A': '迪奥西斯-攻击',
    'Deoxys-D': '迪奥西斯-防御',
    'Deoxys-S': '迪奥西斯-速度',
    'M-Garchomp': 'M-烈咬陆鲨',
    'M-Lopunny': 'M-长耳兔',
    'M-Lucario': 'M-路卡利欧',
    'M-Abomasnow': 'M-暴雪王',
    'M-Gallade': 'M-艾路雷朵',
    'H-Rotom': '加热洛托姆',
    'W-Rotom': '清洗洛托姆',
    'F-Rotom': '结冰洛托姆',
    'Fan-Rotom': '旋转洛托姆',
    'M-Rotom': '切割洛托姆',
    'Giratina-O': '骑拉帝纳-起源',
    'Shaymin-S': '谢米-天空',
    'M-Audino': 'M-差不多娃娃',
    'Darmanitan-Z': '达摩狒狒-达摩模式',
    'Tornadus-T': '龙卷云-灵兽',
    'Thundurus-T': '雷电云-灵兽',
    'Landorus-T': '土地云-灵兽',
    'B-Kyurem': '暗黑酋雷姆',
    'W-Kyurem': '焰白酋雷姆',
    'Keldeo-R': '凯路迪欧-斗士',
    'Meloetta-P': '美洛耶塔-舞步',
    'Ash-Greninja': '小智的甲贺忍蛙',
    'Aegislash-B': '坚盾剑怪-剑形态',
    'Zygarde-10': '基格尔德-10%形态',
    'Zygarde-C': '基格尔德-核心',
    'M-Diancie': 'M-蒂安希',
    'Hoopa-U': '胡帕-解放',
    'Lycanroc-M': '鬓岩狼人-黑夜',
    'Wishiwashi-S': '弱丁鱼-鱼群',
    'Lycanroc-D': '鬓岩狼人-黄昏',
    'Necrozma-S': '奈克洛兹玛-黄昏之鬃',
    'Necrozma-L': '奈克洛兹玛-拂晓之翼',
    'U-Necrozma': '究极奈克洛兹玛',

    //1.1.地图
    'Pallet Town': '真新镇',
    'Viridian City': '常青市',
    'Viridian Forest': '常青森林',
    'Pewter City': '深灰市',
    'Route 0': '0号道路',
    'Route 1': '1号道路',
    'Route 2': '2号道路',
    'Route 3': '3号道路',
    'Route 4': '4号道路',
    'Route 5': '5号道路',
    'Route 6': '6号道路',
    'Route 7': '7号道路',
    'Route 8': '8号道路',
    'Route 9': '9号道路',
    'Route 10': '10号道路',
    'Route 11': '11号道路',
    'Route 12': '12号道路',
    'Route 13': '13号道路',
    'Route 14': '14号道路',
    'Route 15': '15号道路',
    'Route 16': '16号道路',
    'Route 17': '17号道路',
    'Route 18': '18号道路',
    'Route 19': '19号道路',
    'Route 20': '20号道路',
    'Route 21': '21号道路',
    'Route 22': '22号道路',
    'Route 23': '23号道路',
    'Route 24': '24号道路',
    'Route 25': '25号道路',
    'Route 26': '26号道路',
    'Route 27': '27号道路',
    'Route 28': '28号道路',
    'Route 29': '29号道路',
    'Route 30': '30号道路',
    'Route 31': '31号道路',
    'Route 32': '32号道路',
    'Route 33': '33号道路',
    'Route 34': '34号道路',
    'Route 35': '35号道路',
    'Route 36': '36号道路',
    'Route 37': '37号道路',
    'Route 38': '38号道路',
    'Route 39': '39号道路',
    'Route 40': '40号道路',
    'Route 41': '41号道路',
    'Route 42': '42号道路',
    'Route 43': '43号道路',
    'Route 44': '44号道路',
    'Route 45': '45号道路',
    'Route 46': '46号道路',
    'Route 47': '47号道路',
    'Route 48': '48号道路',
    'Route 49': '49号道路',
    'Route 50': '50号道路',
    'Route 51': '51号道路',
    'Route 52': '52号道路',
    'Route 53': '53号道路',
    'Route 54': '54号道路',
    'Route 55': '55号道路',
    'Route 56': '56号道路',
    'Route 57': '57号道路',
    'Route 58': '58号道路',
    'Route 59': '59号道路',
    'Route 60': '60号道路',
    'Route 61': '61号道路',
    'Route 62': '62号道路',
    'Route 63': '63号道路',
    'Route 64': '64号道路',
    'Route 65': '65号道路',
    'Route 66': '66号道路',
    'Route 67': '67号道路',
    'Route 68': '68号道路',
    'Route 69': '69号道路',
    'Route 70': '70号道路',
    'Route 71': '71号道路',
    'Route 72': '72号道路',
    'Route 73': '73号道路',
    'Route 74': '74号道路',
    'Route 75': '75号道路',
    'Route 76': '76号道路',
    'Route 77': '77号道路',
    'Route 78': '78号道路',
    'Route 79': '79号道路',
    'Route 80': '80号道路',
    'Route 81': '81号道路',
    'Route 82': '82号道路',
    'Route 83': '83号道路',
    'Route 84': '84号道路',
    'Route 85': '85号道路',
    'Route 86': '86号道路',
    'Route 87': '87号道路',
    'Route 88': '88号道路',
    'Route 89': '89号道路',
    'Route 90': '90号道路',
    'Route 91': '91号道路',
    'Route 92': '92号道路',
    'Route 93': '93号道路',
    'Route 94': '94号道路',
    'Route 95': '95号道路',
    'Route 96': '96号道路',
    'Route 97': '97号道路',
    'Route 98': '98号道路',
    'Route 99': '99号道路',
    'Route 100': '100号道路',
    'Route 101': '101号道路',
    'Route 102': '102号道路',
    'Route 103': '103号道路',
    'Route 104': '104号道路',
    'Route 105': '105号道路',
    'Route 106': '106号道路',
    'Route 107': '107号道路',
    'Route 108': '108号道路',
    'Route 109': '109号道路',
    'Route 110': '110号道路',
    'Route 111': '111号道路',
    'Route 112': '112号道路',
    'Route 113': '113号道路',
    'Route 114': '114号道路',
    'Route 115': '115号道路',
    'Route 116': '116号道路',
    'Route 117': '117号道路',
    'Route 118': '118号道路',
    'Route 119': '119号道路',
    'Route 120': '120号道路',
    'Route 121': '121号道路',
    'Route 122': '122号道路',
    'Route 123': '123号道路',
    'Route 124': '124号道路',
    'Route 125': '125号道路',
    'Route 126': '126号道路',
    'Route 127': '127号道路',
    'Route 128': '128号道路',
    'Route 129': '129号道路',
    'Route 130': '130号道路',
    'Route 131': '131号道路',
    'Route 132': '132号道路',
    'Route 133': '133号道路',
    'Route 134': '134号道路',
    'Route 135': '135号道路',
    'Route 136': '136号道路',
    'Route 137': '137号道路',
    'Route 138': '138号道路',
    'Route 139': '139号道路',
    'Route 140': '140号道路',
    'Route 141': '141号道路',
    'Route 142': '142号道路',
    'Route 143': '143号道路',
    'Route 144': '144号道路',
    'Route 145': '145号道路',
    'Route 146': '146号道路',
    'Route 147': '147号道路',
    'Route 148': '148号道路',
    'Route 149': '149号道路',
    'Route 150': '150号道路',
    'Route 151': '151号道路',
    'Route 152': '152号道路',
    'Route 153': '153号道路',
    'Route 154': '154号道路',
    'Route 155': '155号道路',
    'Route 156': '156号道路',
    'Route 157': '157号道路',
    'Route 158': '158号道路',
    'Route 159': '159号道路',
    'Route 160': '160号道路',
    'Route 161': '161号道路',
    'Route 162': '162号道路',
    'Route 163': '163号道路',
    'Route 164': '164号道路',
    'Route 165': '165号道路',
    'Route 166': '166号道路',
    'Route 167': '167号道路',
    'Route 168': '168号道路',
    'Route 169': '169号道路',
    'Route 170': '170号道路',
    'Route 171': '171号道路',
    'Route 172': '172号道路',
    'Route 173': '173号道路',
    'Route 174': '174号道路',
    'Route 175': '175号道路',
    'Route 176': '176号道路',
    'Route 177': '177号道路',
    'Route 178': '178号道路',
    'Route 179': '179号道路',
    'Route 180': '180号道路',
    'Route 181': '181号道路',
    'Route 182': '182号道路',
    'Route 183': '183号道路',
    'Route 184': '184号道路',
    'Route 185': '185号道路',
    'Route 186': '186号道路',
    'Route 187': '187号道路',
    'Route 188': '188号道路',
    'Route 189': '189号道路',
    'Route 190': '190号道路',
    'Route 191': '191号道路',
    'Route 192': '192号道路',
    'Route 193': '193号道路',
    'Route 194': '194号道路',
    'Route 195': '195号道路',
    'Route 196': '196号道路',
    'Route 197': '197号道路',
    'Route 198': '198号道路',
    'Route 199': '199号道路',
    'Route 200': '200号道路',
    'Route 201': '201号道路',
    'Route 202': '202号道路',
    'Route 203': '203号道路',
    'Route 204': '204号道路',
    'Route 205': '205号道路',
    'Route 206': '206号道路',
    'Route 207': '207号道路',
    'Route 208': '208号道路',
    'Route 209': '209号道路',
    'Route 210': '210号道路',
    'Route 211': '211号道路',
    'Route 212': '212号道路',
    'Route 213': '213号道路',
    'Route 214': '214号道路',
    'Route 215': '215号道路',
    'Route 216': '216号道路',
    'Route 217': '217号道路',
    'Route 218': '218号道路',
    'Route 219': '219号道路',
    'Route 220': '220号道路',
    'Route 221': '221号道路',
    'Route 222': '222号道路',
    'Route 223': '223号道路',
    'Route 224': '224号道路',
    'Route 225': '225号道路',
    'Route 226': '226号道路',
    'Route 227': '227号道路',
    'Route 228': '228号道路',
    'Route 229': '229号道路',
    'Route 230': '230号道路',
    'Virdian Forest': '常青森林',
    'Mt. Moon': '月见山',
    'Diglett Cave': '地鼠洞穴',
    'Rock Tunnel': '岩山隧道',
    'Power Plant': '无人发电厂',
    'Pokemon Tower': '宝可梦塔',
    'Celadon City': '玉虹市',
    'Saffron City': '金黄市',
    'Safari Zone': '狩猎地带',
    'Trading Center': '交易中心',
    'Seafom Island': '双子岛',
    'Pkmn Mansion': '宝可梦屋',
    'Victory Road': '冠军之路',
    'Cerulean Cave': '华蓝洞窟',
    'Cerulean City': '华蓝城市',
    'Legendary Island': '传说孤岛',
    'The Movie': '电影院',
    'Old Rod': '破旧钓竿',
    'Good Rod': '好钓竿',
    "Let\'s Go : Meltan": '我们走，美录坦',
    'Super Rod': '厉害钓竿',
    //关都结束
    'New Bark Town': '若叶镇',
    'Dark Cave': '黑暗穴',
    'Sprout Tower': '喇叭芽之塔',
    'Ruin of Alph': '阿露福遗迹',
    'Inside the Ruins': '遗迹之内',
    'Union Cave': '互连洞',
    'Slowpoke Well': '呆呆兽之井',
    'Ilex Forest': '桐树林',
    'Daycare House': '培育屋',
    'National Park': '自然公园',
    'Burned Tower': '烧焦塔',
    'Tin Tower': '铃铛塔',
    'Whirl Island': '漩涡列岛',
    'Cianwood City': '湛蓝市',
    'Mt.Mortar': '擂钵山',
    'Rocket Hideout': '火箭队基地',
    'Lake of Rage': '愤怒之湖',
    'Ice Path': '冰雪通路',
    'Dragons Den': '龙穴',
    'Mt.Silver': '白银山',
    'Headbutt': '头槌',
    'Altar of Time': '时之祭坛',
    'Tin Tower 10F': '铃铛塔10层',
    'Whirl Island B2F Inner': '漩涡列岛地下2层内',
    'Felines, Cats or Dogs ?': '传说三圣兽',
    //成都结束
    'Littleroot Town': '未白镇',
    'Petalburg Woods': '橙华森林',
    'Rusturf Tunnel': '卡绿隧道',
    'Granite Cave': '石之洞窟',
    'New Mauville': '新紫堇',
    'Mirage Tower': '幻影之塔',
    'Fiery Path': '热焰小径',
    'Jagged Pass': '凹凸山道',
    'Meteor Falls': '流星瀑布',
    'Weather Institute': '天气研究所',
    'Safari Zone (RS Edition)': '狩猎地带 (红蓝宝石版)',
    'Safari Zone (Emerald Edition)': '狩猎地带 (翡翠版)',
    'Mt. Pyre': '送火山',
    'Too much Hideouts': '太多的藏身处',
    'Mossdeep City': '绿岭市',
    'Shoal Cave': '浅滩洞穴',
    'Mirage Island': '幻之岛',
    'Sky Pillar': '天空之柱',
    'Ruins': '遗迹',
    'Southern Island': '南方孤岛',
    'Cave of Origin': '觉醒祠堂',
    'Sky Pillar (Top)': '天空之柱（顶部）',
    'Wishmaker': '愿望乐园',
    'THE UNIVERSE': '宇宙',
    'Underwater 7.8': '水下 7.8',
    //丰缘结束
    'Twinleaf Town': '双叶镇',
    'Lake Verity': '心齐湖',
    'Oreburgh Gate': '钢铁市之门',
    'Oreburgh City': '钢铁市',
    'Oreburgh Mine': '钢铁市矿山',
    'Floaroma Town': '苑之镇',
    'Valley Windworks': '山谷发电厂',
    '99 Luftballons': '99 红气球',
    'Fuego Ironworks': '多多罗铁工厂',
    'Eterna Forest': '百代森林',
    'Old Chateau': '森之洋馆',
    'Strange TV': '森林洋房',
    'Wayward Cave': '迷幻洞窟',
    'Mt. Coronet': '天冠山',
    'Hearthome City': '缘之市',
    'Hallowed Tower': '灵魂之塔',
    'Lost Tower': '失落之塔',
    'Solaceon Ruins': '随意遗迹',
    'Trophy Garden': '最自豪的后院',
    'Great Marsh': '大湿地',
    'Valor Lakefront': '立志湖前头',
    'Ruin Maniac Cave': '遗迹狂人之洞',
    'Sendoff Spring': '送泉',
    'Turnback Cave': '归途洞窟',
    'Lake Acuity': '睿智湖',
    'Snowpoint Temple': '雪点庙',
    'Iron Island': '钢铁岛',
    'Fight Area': '战斗区',
    'Stark Mountain': '严酷山',
    'Lakes': '湖',
    'Spear Pillar': '枪之柱',
    'Distortion World': '毁坏的世界',
    'Slow Down': '减速',
    'Volcano': '火山',
    'Mysterious Sea': '神秘之海',
    'Moon Island': '月亮岛',
    'Flower Paradise': '花之乐园',
    'Hall of Origin': '初始之间',
    //神奥结束
    'Aspertia City': '桧扇市',
    'Floccesy Ranch': '算木牧场',
    'Virbank Complex': '立涌联合工业区',
    'Castelia City': '飞云市',
    'Castelia Sewers': '飞云地下水道',
    'Desert Resort': '荒野名胜区',
    'Relic Castle': '古代城堡',
    'Ancient Path': '古代小径',
    'Driftveil Drawbridge': '帆巴吊桥',
    'Mistralton Cave': '吹寄洞穴',
    'Chargestone Cave': '电石洞穴',
    'Reversal Mountain': '反转山',
    'Strange House': '陌生者之屋',
    'Nature Preserve': '自然保护区',
    'Celestial Tower': '天堂之塔',
    'Twist Mountain': '罗斯山',
    'Icirrus City': '雪花市',
    'Dragonspiral Tower': '龙螺旋之塔',
    'Moor of Icirrus': '雪花湿地',
    'Village Bridge': '村庄桥',
    'Giant Chasm': '巨人洞窟',
    'Undella Town': '小波镇',
    'Abundant Shrine': '丰饶之社',
    'Marvelous Bridge': '奇幻桥',
    'Lostlorn Forest': '迷幻森林',
    'Undella Bay': '小波湾',
    'Seaside Cave': '海边洞穴',
    'Pinwheel Forest': '矢车森林',
    'Nacrene City': '七宝市',
    'Wellspring Cave': '地下水脉之穴',
    'Dreamyard': '梦的遗址',
    'P2 Laboratory': 'Ｐ２实验室',
    'Shaking Spots': 'Shaking Spots',
    'Just an Illusion': 'Just an Illusion',
    'Relic Castle (Maze End)': '古代城堡（迷宫终点）',
    'Liberty Garden': '自由庭园岛',
    'Pledge Grove': '誓约之林',
    'Weather Guys': '气象专家',
    'Castle of N': 'N之城堡',
    'Giant Chasm (Deep Cave)': '巨人洞窟（深渊）',
    'Serene Grace': '天之恩惠',
    'Not Kabutops': '莫得甲壳虫',
    //合众结束
    'Aquacorde Town': '美川镇',
    'Santalune City': '白檀市',
    'Camphrier Town': '古木镇',
    'Geosenge Town': '石林镇',
    'Coumarine City': '海翼市',
    'Laverre City': '香薰市',
    'Ambrette Town': '古香镇',
    'Anistar City': '百刻市',
    'Couriway Town': '水涟镇',
    'Team Flare Secret HQ': '闪焰队秘密基地',
    'Terminus Cave': '终结洞窟',
    'Queen of Rocks': '岩石女王',
    'The Magician': '魔术师',
    'Steam Siege': '蒸汽围城',
    'Iki Town': '利利小镇',
    'Lush Jungle': '树荫丛林',
    'Special Spots': '特殊地点',
    'Mount Hokulani': '辉克拉尼山',
    'Mount Lanakila': '拉纳基拉山',
    'Welcome to Alola': '欢迎来阿罗拉',
    'Aether Paradise': '以太乐园',
    'Altar': '祭坛',
    'Ultra Wormholes': '超虫洞',
    'Not an Ultra Beast': '不是超级野兽',
    'Not a PokeBall': '不是精灵球',
    'Fighting Ghost': '战斗幽灵',
    'Ultra Volt': '超级伏特',
    'Rod': '杆',
    '': '',
    '': '',

    //左上角的游戏通知
    'Game Loaded': '游戏加载成功',
    'It\'s a new day!': '又到了崭新的一天！',
    'Your Underground deals have been updated.': '你的地下矿场交易更新了。',
    'You have a free quest refresh.': '你有一个免费的任务刷新。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //橡木物品
    'Oak Items': '高级道具',
    'Equip another oak item': '装备另一个高级道具',
    'Magic Ball': '魔法球',
    'Amulet Coin': '护符金币',
    'Poison Barb': '涂毒箭头',
    'Exp Share': '学习装置',
    'Sprayduck': '鸭子喷雾',
    'Shiny Charm': '闪光魅力',
    'Blaze Cassette': '孵化盒',
    'Cell Battery': '太阳能电池',
    'Squirtbottle': '喷药壶',
    'Sprinklotad': '莲叶童子',
    '': '',

    //地下矿场
    '2 Diamonds': '2 钻石',
    '3 Diamonds': '3 钻石',
    '4 Diamonds': '4 钻石',
    '5 Diamonds': '5 钻石',
    '6 Diamonds': '6 钻石',
    '10 Diamonds': '10 钻石',
    'Value': '价值',
    'Sell': '卖',
    'Inv': '拥有数量',
    'Breed': '培育',
    'Daily deals': '每日交易',
    'Max Energy': '最大能量上限',
    'Max items': '最大宝物上限',
    'Min Items': '最小宝物数量',
    'Energy restored': '能量再生数量',
    'Bomb Efficiency': '炸弹效率',
    'Survey Cost': '探查花费能量',
    'Survey Efficiency': '探查效率',
    'Larger underground, +1 Max Item': '更大的地下矿场，1次升满',
    'Skip (': '跳过 (',
    'Bomb (': '炸弹 (',
    'Chisel (': '稿子 (',
    'Hammer (': '锤子 (',
    'Survey (': '随机探查 (',
    'Claw Fossil': '爪子化石',
    'Armor Fossil': '盾甲化石',
    'Plume Fossil': '羽毛化石',
    'Cover Fossil': '背盖化石',
    'Dread Plate': '邪恶板',
    'Earth Plate': '地面板',
    'Fist Plate': '格斗板',
    'Insect Plate': '昆虫板',
    'Sky Plate': '天空板',
    'Spooky Plate': '幽灵板',
    'steel shards': '钢碎片',
    'poison shards': '毒碎片',
    'ice shards': '冰碎片',
    'Icicle Plate': '冰柱板',
    'Iron Plate': '铁板',
    'Toxic Plate': '毒板',
    'Pixie Plate': '精灵板',
    'Meadow Plate': '草甸板',
    'Draco Plate': '龙板',
    'Zap Plate': '速度板',
    'Smooth Rock': '滑石',
    'steel shards': '钢碎片',
    'poison shards': '毒碎片',
    'ice shards': '冰碎片',
    'Icicle Plate': '冰柱板',
    'Iron Plate': '铁板',
    'Toxic Plate': '毒板',
    'Pixie Plate': '精灵板',
    'Meadow Plate': '草甸板',
    'Draco Plate': '龙板',
    'Zap Plate': '速度板',
    'Mind Plate': '心灵板',
    '': '',
    '': '',

    //农场
    'Clear a Plant from a plot.': '从地里清除一颗植物。',
    'Plant All': '全部种植',
    'Harvest All': '全部收获',
    'Shovel': '铲子',
    'Berries': '浆果',
    'Berrydex': '浆果图鉴',
    'Mulch': '农药',
    'Mulch All': '全部农药',
    'Boost Mulch': '生长速度农药',
    'Rich Mulch': '收获数量农药',
    'Surprise Mulch': '基因突变农药',
    'Amaze Mulch': '神奇の农药',
    'Flavor': '味道',
    'Spicy': '辣',
    'Dry': '干',
    'Sweet': '甜',
    'Bitter': '苦',
    'Sour': '酸',
    'Growth Stages': '生长阶段',
    'Sprout': '发芽',
    'Taller': '长大',
    'Bloom': '开花',
    'Berry': '浆果',
    'Harvest': '收获',
    'Description': '介绍',
    'Growth Time': '生长时间',
    'Harvest Amount': '每颗果树收获量',
    'Replant Rate': '死亡后重新种植概率',
    'Farm Points per Harvest': '每颗果树可收获农场币',
    'Harvested': '收获数',
    'Hint': '提示',
    'I\'ve heard that a special Berry can appear after being surrounded by': '我听说一种特殊的浆果会在被包围后出现，用',
    'berries at the farm': '浆果，从农场里',
    '': '',

    //剧情
    'Mystery of Deoxys': '神秘的代欧奇希斯',
    'Discover the mystery of Deoxys': '探索神秘的代欧奇希斯',
    '': '',
    '': '',

    //1.2.待归类
    '---': '———',
    'pokeball': '精灵球',
    'greatball': '超级球',
    'ultraball': '高级球',
    'EASY': '简单',
    'MEDIUM': '中等',
    'HARD': '困难',
    'IMPOSSIBLE': '不可能',
    'Oak': '橡树',
    'Light Clay': '轻粘土',
    'Double the chance to encounter a shiny Pokemon': '双倍机会遇到闪光宝可梦',
    'Gain 25% more exp from wild Pokemon': '从野生宝可梦获得的经验 +25％',
    'Gain 50% more coins from wild Pokemon': '从野生宝可梦获得的金钱 +50％',
    'Get a 10% bonus to your catchRate': '捕捉几率 +10%',
    'Regenerate 50% more mining energy!': '采矿能量恢复 +50%',
    'With this rod you are able to catch water Pokemon': '有了这根杆，你就可以捕捉水中的口袋妖怪',
    'Your clicks do 25% more damage!': '你的点击造成的伤害 +25％！',
    'Your eggs will hatch twice as fast!': '孵蛋速度 x2',
    'Electric Egg': '电蛋',
    'electric shards': '电碎片',
    'Clicks do 150% more damage': '点击伤害 +150%',
    'Gain 30% more money': '获得金钱 +30%',
    'quest': '任务',
    'Hatchery': '培育室',
    'Day Care': '日托',
    'Shortcuts': '便捷入口',
    'Thunder Stone': '雷石',
    'Thunder': '雷',
    'Rainbow': '彩虹',
    'Erika': '埃里卡',
    'Clicks do 200% more damage': '点击伤害 +200%',
    'Celadon City Gym': '玉虹市道馆',
    'Cerulean City Gym': '华蓝城市道馆',
    'Cinnabar Island Gym': '朱砂岛道馆',
    'Fuchsia City Gym': '浅红市道馆',
    'Indigo Plateau Gym': '靛蓝高原道馆',
    'Pewter City Gym': '深灰市道馆',
    'Saffron City Gym': '金黄市道馆',
    'Vermillion City Gym': '朱红色城市道馆',
    'Viridian City Gym': '常青市道馆',
    'dome': '圆顶',
    'Damp Rock': '湿岩',
    'Max Revive': '最大复活',
    'Digletts Cave Dungeon': '地鼠洞地牢',
    'Odd Keystone': '钥匙石',
    'Star Piece': '星片',
    'A fighting egg.': '一个战斗蛋。',
    '': '',
    '': '',
    '': '',
    '': '',

    //1.3.防具

    //速度
    'Medium Slow': '中等慢',
    'Medium Fast': '中等快',
    'Fast': '快',
    'Slow': '慢',
    //属性
    'electric': '电',
    'flying': '飞行',
    'rock': '岩石',
    'ice': '冰',
    'fairy': '妖精',
    'normal': '一般',
    'ground': '地面',
    'psychic': '超能力',
    'dark': '恶',
    'grass': '草',
    'ghost': '幽灵',
    'fighting': '格斗',
    'dragon': '龙',
    'water': '水',
    'bug': '虫',
    'steel': '钢',
    'fire': '火',
    'poison': '毒',
    'Electric': '电',
    'Flying': '飞行',
    'Rock': '岩石',
    'Ice': '冰',
    'Fairy': '妖精',
    'Normal': '一般',
    'Ground': '地面',
    'Psychic': '超能力',
    'Dark': '恶',
    'Grass': '草',
    'Ghost': '幽灵',
    'Fighting': '格斗',
    'Dragon': '龙',
    'Water': '水',
    'Bug': '虫',
    'Steel': '钢',
    'Fire': '火',
    'Poison': '毒',
    'ELECTRIC': '电',
    'FLYING': '飞行',
    'ROCK': '岩石',
    'ICE': '冰',
    'FAIRY': '妖精',
    'NORMAL': '一般',
    'GROUND': '地面',
    'PSYCHIC': '超能力',
    'DARK': '恶',
    'GRASS': '草',
    'GHOST': '幽灵',
    'FIGHTING': '格斗',
    'DRAGON': '龙',
    'WATER': '水',
    'BUG': '虫',
    'STEEL': '钢',
    'FIRE': '火',
    'POISON': '毒',
    //1.4.升级
    'Catch time upgrade I': '捕捉时间升级 I',
    'Catch time upgrade II': '捕捉时间升级 II',
    'Catch time upgrade III': '捕捉时间升级 III',
    'Catch time upgrade IV': '捕捉时间升级 IV',
    'Catch time upgrade V': '捕捉时间升级 V',
    'Click multiplier upgrade I': '点击加成升级 I',
    'Click multiplier upgrade II': '点击加成升级 II',
    'Click multiplier upgrade III': '点击加成升级 III',
    'Click multiplier upgrade IV': '点击加成升级 IV',
    'Click multiplier upgrade V': '点击加成升级 V',
    'Clicks do 100% more damage': '点击伤害翻倍',
    'Decrease the catch time by 250 milliseconds': '将捕捉时间减少250毫秒',
    'Experience upgrade I': '经验升级 I',
    'Experience upgrade II': '经验升级 II',
    'Experience upgrade III': '经验升级 III',
    'Experience upgrade IV': '经验升级 IV',
    'Experience upgrade V': '经验升级 V',
    'Gain 25% more money': '获得金钱 +25%',
    'Money multiplier upgrade I': '金钱倍数升级 I',
    'Money multiplier upgrade II': '金钱倍数升级 II',
    'Money multiplier upgrade III': '金钱倍数升级 III',
    'Money multiplier upgrade IV': '金钱倍数升级 IV',
    'Money multiplier upgrade V': '金钱倍数升级 V',
    'New technology gives you a 10% bonus to experience gain': '新技术给你带来 +10% 的经验获得',
    'New technology gives you a 5% bonus to catch rate': '新技术给你带来 +5% 的抓捕几率',
    'Pokeball upgrade I': '精灵球升级 I',
    'Pokeball upgrade II': '精灵球升级 II',
    'Pokeball upgrade III': '精灵球升级 III',
    'Pokeball upgrade IV': '精灵球升级 IV',
    'Pokeball upgrade V': '精灵球升级 V',
    'Token Collector': '令牌收集器',
    'xAttack': 'X攻击',
    'xClick': 'X点击',
    'coins': '金钱',
    'X Exp': 'X 经验',
    'quest points': '任务点',
    'Random Egg': '随机蛋',
    'X Attack': 'X 攻击',
    'X Click': 'X 点击',
    'Brock': '坏蛋',
    'Dome Fossil': '圆顶化石',
    'Helix Fossil': '螺旋化石',
    'Iron Ball': '铁球',
    'Old Amber': '旧琥珀',
    'diamonds': '钻石',
    'money': '金钱',
    'Lucky Egg': '幸运蛋',
    'Lucky Incense': '幸运香',
    'Viridian Forest Dungeon': '常青森林地牢',
    'Misty': '米丝蒂',
    'Normal Rod': '普通棒',
    'Mt. Moon Dungeon': '月见山地牢',
    'Lt. Surge': 'Lt.浪涌',
    'Fighting Egg': '战斗蛋',
    'grass shards': '草碎片',
    'Lavender Town': '薰衣草镇',
    'Leaf Stone': '叶石',
    'Moon Stone': '月石',
    'Grass Egg': '草蛋',
    'Item Magnet': '物品磁铁',
    'Water Egg': '水蛋',
    'water shards': '水碎片',
    'Water Stone': '水石',
    'Gain 35% more money': '获得的金钱 +35%',
    'Gain 40% more money': '获得的金钱 +40%',
    'Sabrina': '萨布丽娜',
    'Rock Tunnel Dungeon': '岩山隧道地牢',
    'Pokemon Tower Dungeon': '宝可梦塔地牢',
    'Rare Bone': '稀有骨头',
    'Hard Stone': '硬石',
    'Icy Rock': '冰石',
    'Boulder': '圆石',
    'Cascade': '喷流',
    'New technology gives you a 10% bonus to catch rate': '新技术给你 +10% 的捕捉绿。',
    'Power Plant Dungeon': '无人发电厂地牢',
    'Legendary Charm': '传奇魅力',
    'Gain 50% more money': '获得的金钱 +50%',
    '50% more chance to encounter a legendary Pokemon': '遇到传奇宝可梦的几率 +50％',
    'Blaine': '布莱恩',
    'Cerulean Cave Dungeon': '华蓝洞窟地牢',
    'Dragon Egg': '龙蛋',
    'Earth': '土',
    'Fire Egg': '火蛋',
    'fire shards': '火碎片',
    'Fire Stone': '火石',
    'Giovanni': '乔凡尼',
    'Heart Scale': '心脏秤',
    'Indigo Plateau': '靛蓝高原',
    'Koga': '四郎',
    'Legendary Charm': '传奇魅力',
    'Marsh': '沼泽',
    'New technology gives you a 20% bonus to experience gain': '新技术让你获得的经验 +20%',
    'Pokemon Mansion Dungeon': '宝可梦屋地牢',
    'Seafoam Islands Dungeon': '双子岛地牢',
    'Soul': '灵魂',
    'Splash Plate': '防溅板',
    'Trade Stone': '贸易石',
    'Victory Road Dungeon': '冠军之路地牢',
    'dragon shards': '龙碎片',
    'psychic shards': '精神碎片',
    'rock shards': '岩石碎片',
    'Stone Plate': '石板',
    'Sun Stone': '日石',
    'Double your chance of getting items for 60 seconds!': '在60秒内获得物品的几率翻倍！',
    'Double your click attack for 60 seconds!': '在60秒内你的点击攻击翻倍！',
    'Double your Pokemons attack for 60 seconds!': '在60秒内你的宝可梦的攻击翻倍！',
    'Double the money you earn for 60 seconds!': '在60秒内你获得的金钱翻倍！',
    'Double the exp you earn for 60 seconds!': '在60秒内你获得的经验翻倍',
    'Double the dungeon tokens you earn for 60 seconds!': '在60秒内你获得的地牢令牌翻倍',
    'A peculiar stone that makes certain species of Pokemon evolve. It has a thunderbolt pattern.': '一种奇特的石头，使某些种类的口袋妖怪进化。 它有霹雳模式。',
    'A peculiar stone that makes certain species of Pokemon evolve. It is colored orange.': '一种奇特的石头，使某些种类的口袋妖怪进化。 它是橙色的。',
    'A peculiar stone that makes certain species of Pokemon evolve. It has a leaf pattern.': '一种奇特的石头，使某些种类的口袋妖怪进化。 它有叶子图案。',
    'A peculiar stone that makes certain species of Pokemon evolve. It is a clear light blue.': '一种奇特的石头，使某些种类的口袋妖怪进化。 它是一种清澈的浅蓝色。',
    'A peculiar stone that makes certain species of Pokemon evolve. It is as black as the night sky.': '一种奇特的石头，使某些种类的口袋妖怪进化。 它像夜空一样黑。',
    'A peculiar stone that makes certain species of Pokemon evolve. It looks very lonely.': '一种奇特的石头，使某些种类的口袋妖怪进化。 它看起来很孤单。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //1.5.统计
    'Catch Bonus': '捕捉奖励',
    'Catch Time': '捕捉时间',
    'Champion': '冠军',
    'Cinnabar Island': '朱砂岛',
    'Click Attack': '点击伤害',
    'Clicks': '点击次数',
    'Current values': '当前数',
    'Diamonds': '钻石',
    'Digletts Cave': '地鼠洞',
    'Dungeons Cleared': '清理地牢',
    'Eggs Hatched': '孵蛋',
    'Elite Agatha': '精英阿加莎',
    'Elite Bruno': '精英布鲁诺',
    'Elite Four': '精英四人组',
    'Elite Lance': '精英兰斯',
    'Elite Lorelei': '精英洛雷莱',
    'Exp Multiplier': '经验倍数',
    'Fuchsia City': '浅红市',
    'Gyms Defeated': '打败道馆',
    'Items Found': '找到物品',
    'Money': '金钱',
    'Money Multiplier': '金钱倍数',
    'Pokemon Attack': '宝可梦攻击',
    'Pokemon Mansion': '宝可梦屋',
    'Pokemons Defeated per route': '每条道路打败的宝可梦',
    'Quest Points': '任务点',
    'Seafoam Islands': '双子岛',
    'Total Captures': '总捕捉数量',
    'Total Pokemon Defeated': '总共打败的宝可梦',
    'Total values': '总数',
    'Unique Pokemon': '独特宝可梦',
    'Unique Shinies': '独特闪光',
    'Vermillion City': '朱红色城市',
    '': '',
    '': '',
    //2020.10.12新版本内容
    'Save': '保存',
    'Settings': '设置',
    'Shop': '商店',
    'Sort': '排序',
    'Start': '开始',
    'Start Menu': '开始菜单',
    'Convert': '转换',
    'Congratulations!': '恭喜!',
    'Eggs': '蛋',
    'egg': '蛋',
    'Event': '事件',
    'Events': '事件',
    'Filters': '过滤',
    'All': '全部',
    'Attack': '攻击',
    'Attack Bonus': '攻击加成',
    'Atk': '攻击',
    'CAUGHT': '捕捉',
    'Caught': '捕捉',
    'SHINY': '闪光',
    'QUEST': '任务',
    'Click': '点击',
    'Click Attack:': '点击伤害:',
    'Click Attacks': '点击伤害',
    'Close': '关闭',
    'Items': '物品',
    'ESCAPED': '挣脱',
    'FOUND': '发现',
    'ACHIEVE': '成就',
    'Achievements': '成就',
    'Achievements Bonus': '成就加成',
    'Amount': '数量',
    'amount': '数量',
    'Auto refresh Daily Deals when upgrade purchased': '购买升级后自动刷新每日优惠',
    'Bait': '诱饵',
    'Bonus': '加成',
    'CHANGE': '更改',
    'Changelog': '更新日志',
    'Cost': '成本',
    'Damage': '伤害',
    'Diamond': '钻石',
    'energy': '能量',
    'Level': '等级',
    'List': '列表',
    'Loading...': '加载中...',
    'Lvl': '等级',
    'Lvl.': '等级',
    'Max': '最大',
    'MAX LEVEL!': '最高级！',
    'Message': '消息',
    'Modal title': '弹框标题',
    'Refresh': '刷新',
    'Region': '地区',
    'Reset': '重置',
    'Quit Battle': '退出战斗',
    'REMOVED': '已删除',
    'Report a bug': '上报Bug',
    'Reset All': '全部重置',
    'Route Kill': '特杀',
    'Stage': '阶段',
    'Status': '状态',
    'Start Time': '开始时间',
    'Step count': '步数',
    'EVENT': '事件',
    'Explore': '探索',
    'Farm': '农场',
    'Farm Points': '农场点数',
    'Hatch': '孵化',
    'Hatched': '已孵化',
    'Hatch Steps': '孵化步骤',
    'Import Save': '导入存档',
    'Item': '物品',
    'Theme': '主题',
    'Trade': '贸易',
    'Type': '类型',
    'Type Detail': '类型详情',
    'Underground': '地下矿场',
    'Unlock': '解锁',
    'UPDATE': '更新',
    'Update maps': '更新地图',
    'Item Name': '物品名称',
    'Help': '帮助',
    'Achievement Tracker': '成就追踪器',
    'Achievement Description': '成就描述',
    'Poké Mart': '精灵超市',
    'Pokéballs': '精灵球',
    'Pokeball': '精灵球',
    'Masterball': '大师球',
    'PokéBall bag': '精灵球袋',
    'Small Restore': '初级体力药剂',
    'Medium Restore': '中级体力药剂',
    'Large Restore': '高级体力药剂',
    'Pokédex!': '图鉴！',
    'Pokédex': '图鉴',
    'Pulse': '脉冲',
    'Protein': '营养液',
    'Proteins Used': '营养液使用次数',
    'Base Attack': '基础攻击',
    'Base Attack Only': '仅基础攻击',
    'Battle Items': '战斗物品',
    'Badge Case': '徽章盒',
    'Solar': '太阳',
    'Sound': '声音',
    'Sold Out': '卖光了',
    'Statistics': '统计',
    'Statistic': '统计',
    'Gym': '健身馆',
    'Halloween!': '万圣节！',
    'Log Book': '日志簿',
    'Shards': '碎片',
    'Download Save': '下载存档',
    'Damage Calculator': '伤害计算器',
    'Name': '名称',
    'List': '列表',
    'Attack:': '攻击:',
    'Town Map': '城镇地图',
    'Town Name': '城镇名称',
    'Travel To Next Region': '前往下一个地区',
    'Travel to next region': '前往下一个地区',
    'Treasures': '宝物',
    'Uncaught': '未抓到',
    'Quit': '退出',
    'Quests Completed': '任务完成',
    'Removed Time Stone': '移除时间之石',
    'Reward': '奖励',
    'Route': '道路',
    'New maps': '新地图',
    'NEW': '新',
    'New': '新',
    'name': '名称',
    'Night': '夜晚',
    'None': '无',
    'Not Shiny': '非闪光',
    'NPC Name': 'NPC名称',
    'number': '数字',
    'Next': '下一个',
    'Other': '其它',
    'Pokéclicker': '宝可梦点击 - Pokéclicker',
    'Professor Oak': '橡木教授',
    'Tutorial Quests': '程任务',
    'Game loaded': '游戏已加载',
    'Seconds Played': '已玩游戏时长',
    'End Time': '结束时间',
    'Ball': '精灵球',
    'Done': '完成',
    'Catch Rate': '捕获率',
    'Caught Pokemon': '抓到的宝可梦',
    'Defeated': '已击败',
    'Encountered': '遇到',
    'Dig': '挖',
    'Coin case': '硬币盒',
    'Teachy tv': '无线电视',
    'Claim': '要求',
    'Battle Points': '战斗点数',
    'Captured': '已抓到',
    'Underground Items Found': '找到的地下物品',
    'Underground Layers Mined': '地下开采层数',
    'Underground Entrance': '地下矿场',
    'Token': '代币',
    'Token collector': '代币收集器',
    'Time based evolutions': '基于时间的进化',
    'Convert Original Save': '转换原始存档',
    'Current Attack': '当前攻击',
    'Current save data should be compatible with future versions': '当前的存档数据应与将来的版本兼容',
    'Do not catch': '不捕捉',
    'Dock': '码头',
    'Display Value': '显示值',
    'Dungeon name': '地牢名称',
    'Dungeon Time': '地牢时间',
    'Dungeon Master': '地牢主人',
    'Egg hatched': '孵化的蛋',
    'Egg hatched a shiny': '孵化出来一只闪光宝可梦',
    'Egg Steps': '蛋品阶',
    'Egg ready to hatch': '准备孵化的蛋',
    'Egg Hatching Animation': '孵蛋动画',
    'Eggs now have multiple different styles': '蛋现在有多种风格',
    'Encountered a shiny Pokemon': '遇到了一只闪光宝可梦',
    'Enemy pokemon dropped an item': '敌方宝可梦掉落了一个物品',
    'Energy regen time': '能量再生时间',
    'Even more unfortunately,': '更不幸的是，',
    'Fire stone': '火石',
    'Evolution stones': '进化石',
    'More events': '更多事件',
    'Never': '从不',
    'New achievement earned': '获得新成就',
    'New evolution stones': '新进化石',
    'New key item': '新关键物品',
    'New Pokémon/shiny captured': '抓到新宝可梦/闪光',
    'Note': '注意',
    'Rare Hold Item': '稀有物品',
    'Shards Gained': '获得碎片',
    'Alola': '阿罗拉',
    'Almost & fully ready': '几乎准备就绪',
    'Underground is open': '地下矿场是开放的',
    'Farm is open': '农场是开放的',
    'Day Care is open': '日托是开放的',
    'You will gain': '你将获得',
    'fossil': '化',
    'Fossils will now show in the Hatchery': '化石现在将出现在培育室',
    'Free quest refreshes': '免费任务刷',
    'Free Refresh': '免费刷',
    'Fully ready': '全部准备就',
    'Game controls will be ignored if focused on an input element': '游戏控件将被忽略，如果集中在一个输入元',
    'Game should now load in older versions of Firefox': '游戏现在应该加载到旧版本的火狐',
    'Game will still load if not all the images preload correctly': '所有图片预加载正确前，游戏将一直加',
    'Gastrodon (east': '海兔兽（东海',
    'Format numbers in shop and Pokéball selector': '在商店和神奇宝贝球选择器中设置数字格式',
    'Gastrodon (east) on route 213.': '海兔兽（东海）在道路213',
    'Gastrodon (west': '海兔兽（西海',
    'Give free quest refresh on all quests completed': '所有任务完成后将给与免费任务刷新',
    'Gives a bonus to your catchrate': '提高捕捉率',
    'Glameow on route 218.': '魅力喵在道路218',
    'Going to the breeder will no longer send you to route': '去培育员那里将不再把你送到道路中',
    'Gym leader defeated': '道馆馆主已击败',
    'Gym Pokémon can no longer be captured by players': '道馆宝可梦不再可以被玩家捕捉',
    'Gyms and Dungeons in the Johto and Hoenn regions have been buffed': '都城和丰缘地区的道馆和迷宫已被加强',
    'Gyms no longer reset 1 second in': '道馆不再重置为1秒',
    'Gyms should award correct amount of Egg steps now': '道馆现在可以奖励正确的孵蛋步数了',
    'Halloween': '万圣节',
    'Halve xp needed to upgrade Oak items': '高级道具升级经验减半',
    'Hammer will mine 1 layer on all nine tiles of a 3x3 square.': '锤子能在3X3区域的9块地砖上开采1层',
    'Hatchery eggs will display in a row of 4 when module is in the middle columnn': '当模块位于中间列时，孵化卵将显示为4行',
    'More Farm statistics': '更多农场统计数据',
    'More items added to underground': '更多物品添加到地下矿场',
    'More notification settings have been added': '已添加更多通知设置',
    'More NPCs added around the regions': '在这些地区增加了更多的NPC',
    'More NPCs in towns around Johto and Hoenn': '城都地区 和 丰缘地区 附近的城镇 增加了更多的NPC',
    'More Pokémon added to typed eggs': '更多的宝可梦加入到蛋中',
    'More Pokémon held items added': '添加了更多宝可梦物品',
    'More shops added to towns': '城镇里增加了更多的商店',
    'More statistics added': '添加了更多统计信息',
    'More statistics have been added': '增加了更多的统计数据',
    'Modified Sinnoh route difficulty': '改良 深奥地区 路线难度',
    'Modified the look of the dock': '修改码头的外观',
    'Modified the way game ticks are handled': '修改了游戏滴答声的处理方式',
    'Modules can now be sorted/arranged any way you like, just drag and drop': '模块现在可以按您喜欢的方式进行排序/排列，只需拖放即可',
    'More stores and items added in Johto, Hoenn and Sinnoh': '城都、丰缘和神奥地区，增加了更多商店和商品',
    'Move battle item container': '移动战斗物品箱',
    'Move some dungeons to be standalone': '改变一些地牢位置成为独立的',
    'Moved shiny icon further into the corner in the Day Care view, to make it easier to spot already shiny Pokémon': '将闪光图标进一步移到日托视图的角落，以便更容易发现已经闪光的宝可梦',
    'Mt. Chimney dungeon is now more powerful': '烟囱山地牢现在更强大了',
    'Mulches': '农药',
    'Mulches can be bought in later regions from Berry Masters,': '农药可以在以后的地区从浆果大师那里买到，',
    'Mulches Used': '使用的农药',
    'Mutations': '基因突变',
    'My name is Oak, People affectionately refer to me as the Pokémon Professor.': '我叫Oak，人们亲切的称我为宝可梦教授。',
    'Mystery egg': '神秘蛋',
    'Mystery egg can now hatch Pokémon from the Dragon Egg pool': '神秘蛋现在可以从龙蛋池孵化宝可梦了',
    'Nerfed egg steps for evolved Pokémon forms': '进化的宝可梦形式的削弱蛋步骤',
    'Map tooltips not always showing': '地图工具提示不是总显示',
    'Materia': '材料',
    'Max Level Oak Item': '最高等级高级物品',
    'Mesprit and Cresselia are now roaming in Sinnoh': '艾姆利多 和 克雷色利亚 现在正在辛诺漫游',
    'Mewtwo strikes back': '超梦的逆袭',
    'Mine data contained in save data': '保存数据中包含的挖掘数据',
    'Mine should no longer soft lock players': '我的应该不会再软锁玩家了',
    'Mining energy reached maximum capacity': '采矿能量达到最大容量',
    'Minor display and text fixes': '次要显示和文本修复',
    'Minor text fixes': '次要文本修复',
    'Misc text changes': '杂项文本更改',
    'Manual Harvests': '手动收获',
    'Map is able to be hidden now': '地图现在可以隐藏了',
    'Some Gyms and Dungeons HP buffed': '一些道馆和地牢的生命值得到了强化',
    'Some items showing _ in their name in notifications': '某些项目在通知中以其名称显示',
    'Some minor Discord integration': '一些小的不和谐整合',
    'Some Pokémon now have a chance to drop rare items upon defeat': '一些宝可梦现在有机会在失败时掉落稀有物品',
    'Some Roaming Pokémon will only appear after certain requirements have been met': '一些漫游宝可梦只有在满足某些要求后才会出现',
    'Some upgrades will make the Underground harder and are less cost efficient.': '一些升级将使地下更困难，成本效益较低。',
    'Sounds will now play if enabled even if the notification is disabled': '即使通知被禁用，如果启用声音也会播放',
    'Spacelab': '太空实验室',
    'Special events can now appear in game': '特殊事件现在可以出现在游戏中',
    'Sprout images displayed in Farm': '农场中显示的芽苗菜图像',
    'Sketchy theme checkboxes and close icons should display correctly now': '草主题背景图复选框和关闭图标现在应正确显示',
    'Skull Fossil': '头骨化石',
    'Slate': '石板',
    'So, you won! Congratulations': '所以，你赢了！祝贺',
    'Some battle background images were not showing, they should now appear correctly': '有些战斗背景图像没有显示，现在应该正确显示了',
    'Some Dungeon Pokémon will only appear after certain requirements have been met': '一些地下城神奇宝贝只有在满足某些要求后才会出现',
    'Sinnoh Route': '神奥道路',
    'Show the hatchery "list" button once Johto unlocked without page refresh': '显示孵化场 "列表" 按钮后， 城都地区 无需页面刷新即可解锁',
    'Show the reason you cannot access a location': '显示无法访问位置的原因',
    'Side cards can now be collapsed for more space': '侧牌现在可以折叠以获得更多空间',
    'Shop prices should no longer overflow when too large': '商店价格太大时不应再溢出',
    'Shops will now only show the balance of currencies used there': '商店现在将只显示那里使用的货币余额',
    'shovels can be purchased in later regions from Berry Masters': '铲子可以在以后的地区从浆果大师购买',
    'Shovels Used': '使用的铲子',
    'Show battle item names and descriptions': '显示战斗项目名称和说明',
    'Show Berry hints in BerryDex': '在浆果商店处显示浆果提示',
    'Show currency gained animation': '显示获得货币的动画',
    'Show currently locked Dungeon Bosses': '显示当前锁定的地牢老板',
    'Show event Pokémon in the Pokédex': '在宝可梦中显示宝可梦事件',
    'Show Oak Item details on hover on main screen': '在主屏幕上悬停显示高级道具的详细信息',
    'Show Pokéball image by caught Pokémon in the Pokédex': '在精灵球中捕获的宝可梦显示宝可梦图像',
    'Remove old game codes': '删除旧的游戏代码',
    'Revive': '恢复',
    'Ripe Berry plants may attract wild Pokémon that will join your party. Some Pokémon can only be found using certain Berry species.': '成熟的浆果植物可能会吸引野生宝可梦加入你的队伍。有些神奇宝贝只能使用某些浆果吸引。',
    'Ripe/Death': '成熟/死亡',
    'Roaming Pokémon chance of appearing is now based on route difficulty': '漫游的宝可梦现在在更难的道路上出现的几率更高',
    'Rock (∞': '岩石 （∞',
    'Rock: Throwing a rock will make the Pokémon more likely to flee, but easier to catch': '岩石： 扔石头会使神奇宝贝更容易逃跑， 但更容易被抓住',
    'Root Fossil': '根化石',
    'Reduce svg image sizes, fix some lag': '减少 svg 图像大小，修复一些滞后',
    'Reduce screen movement on mobile battle view': '减少移动战斗视图上的屏幕移动',
    'Reduce some checks firing too often': '减少一些太频繁的检查',
    'Recalculate Pokémon attack upon hatch': '孵化后重新计算宝可梦的攻击',
    'Reduce lag when hatching Pokémon': '减少孵化宝可梦的时间',
    'Queue Slots Full': '队列插槽已满',
    'Quest not completing if restarted after being quit': '如果退出任务后重新启动，任务则未完成',
    'Questline progress restored correctly': '正确恢复任务线进度',
    'Quests list not auto refreshed on new day or level up': '任务列表未在新的一天或升级时自动刷新',
    'Wormadam (plant': '结草贵妇',
    'Very': '非常',
    'Wailmer pail unlocks at 3 Cheri berries instead of': '吼吼鲸桶解锁于 3个樱桃， 而不是',
    'Walking in the Safari Zone will now add steps to your eggs': '走在野生动物园区现在将增加孵蛋的步数进度',
    'Wandering Pokémon': '流浪宝可梦',
    'When hatching shop eggs, the Pokémons level will no longer be reset': '孵化间孵出的蛋，这个宝可梦等级将不再重置',
    'When you are ready, click Start': '准备就绪后，单击"开始"',
    'When you have encountered a Pokémon, you will be given 4 options': '当你遇到宝可梦时，你将得到4个选项',
    'Quest changing when traveling to a new region': '前往新的地区时 任务更改',
    'Quest level increased': '任务级别增加',
    'You have grown up so much since you first left with': '自从你第一次离开， 你长大了这么多',
    'Your breeding queue is full.': '您的孵化队列已满。',
    'Your safari exploration will end when you have run out of Pokéballs.': '当您用完精灵球时，您的野生动物园探索将结束。',
    'wild Chatot escaped': '野生的 聒噪鸟 逃脱',
    'wild Croagunk escaped': '野生的 不良蛙 逃脱',
    'wild Finneon escaped': '野生的 荧光鱼 逃脱',
    'wild Gastrodon (east) escaped': '野生的 海兔兽 逃脱',
    'wild Mime Jr. escaped': '野生的 魔尼尼 逃脱',
    'wild Shellos (east) escaped': '野生的 无壳海兔 逃脱',
    'will no longer evolve into evolutions you have already obtained': '将不再进化成你已经获得的进化',
    'You can spend some mining energy to conduct a Survey.': '你可以花一些采矿能量来进行调查。',
    'you can use a Shovel to uproot it.': '您可以使用铲子把它连根拔起。',
    'You can use your diamonds to buy all kinds of upgrades that will help you explore the underground even further': '您可以使用您的钻石购买各种升级，这将有助于您进一步探索地下',
    'You can view all your': '您可以查看所有',
    'You do not get any rewards for resetting your savefile': '重置保存文件不会获得任何奖励',
    'you don\'t have any eggs to breed.': '你没有更多的蛋可以繁殖',
    'you don\'t have any fossils to breed.': '你没有更多的化石可以繁殖。',
    'You don\'t have any free eggslots.': '你没有更多的免费的蛋。',
    'You don\'t have any treasures yet...': '你还没有宝藏...',
    'You have gained a': '您已经获得了一个',
    'You are the new Pokémon League champion': '你是新的宝可梦联盟冠军',
    'You can click on it to inflict damage': '你可以点击它来造成伤害',
    'You can disable auto download in the settings': '您可以在设置中禁用自动下载',
    'You can now travel on to': '您现在可以前往',
    'You can paste your old PokéClicker save file here, to keep shinies': '您可以在此处粘贴您的旧版 宝可梦点击 保存文件，以保持闪亮',
    'You can progress to the next route after you have defeated 10 pokémon.': '击败10只宝可梦后，你可以到达下一条路线',
    'Drifloon on route 205.': '飘飘球在道路205',
    'Dungeon based evolutions': '基于进化的迷宫',
    'Dungeon Grinder': '迷宫研磨机',
    'Added Protein trade to Sinnoh Berry Master': '添加营养液到神奥地区的浆果大师处。',
    'Added region filter to Pokédex': '在图鉴中添加了区域过滤器。',
    'Added setting for Hatchery egg ready to hatch animations': '添加了孵化场蛋准备孵化动画的设置。',
    'Added setting for shop value increment amount': '增加了店铺价值增量的设置',
    'Added shortcut module': '新增快捷模块',
    'Added some more NPC around Kanto': '增加了一些关东周边的NPC',
    'Added sort dropdown to the Hatchery': '在孵化器中添加了排序下拉菜单',
    'Added sounds for specific events': '增加了特定事件的声音',
    'Added statistic for Hatched Shiny Pokémon': '添加了孵化的闪光宝可梦的统计资料。',
    'Added the Battle Frontier in the Hoenn region': '增加了丰缘地区的战役边境。',
    'Added toggle to hide shiny images in Pokédex': '在图鉴中添加了隐藏闪光图像的选项。',
    'Added volume control for notification sounds': '增加了通知音的音量控制',
    'Added weather to the regions': '在各地区增加了天气预报',
    'Additional plots can be unlocked by spending Berries.': '额外的地块可以通过花费浆果解锁。',
    'After paying the entrance fee, you will be able to walk around in the safari zone. To encounter Pokémon, you must walk in tall grass.': '交完入场费后，就可以在野生动物园区走动。要想遇到宝可梦，必须在高高的草地上行走。',
    'After your turn of the encounter, if it did not result in the encounter ending, the wild Pokémon will have a chance of running away.': '在你的战斗回合后，如果没有导致战斗结束，野生的宝可梦将有几率逃跑。',
    'All eggs will auto hatch when steps reached if Pokémon still in the queue': '如果有宝可梦还在队列中，当达到步骤时，所有蛋将自动孵化。',
    'All Happiness/Friendship evolutions now make use of the Soothe Bell': '所有的幸福/友谊进化现在都可以使用安抚钟',
    'All Hoenn Pokémon should be obtainable now': '所有的丰缘地区宝可梦应该可以获得了。',
    'Allow better control of which type of ball to use when capturing a Pokémon': '可以更好地控制捕捉宝可梦时使用哪种类型的球。',
    'Alternate Form Pokémon statistics shown correctly': '备用形态宝可梦统计正确显示',
    'alternate forms can now be obtained': '现在可以获得其他形式',
    'Always add caught Shiny Pokémon to the Log Book': '捕捉到的闪闪发光的宝可梦一定要添加到记录本上。',
    'Always show total levels in Oak Item tooltips': '总是在高级道具提示中显示总等级。',
    'amount based on Quest Level': '基于任务等级的金额',
    'Animate town and dungeon background images': '动画城镇和地下城背景图片',
    'Battle Frontier': '战斗疆场',
    'Battle Frontier Highest Stage Completed': '战斗前线最高阶段完成',
    'Battle Frontier Total Stages Completed': '战争前线已完成的阶段总数',
    'Battle item about to wear off': '战斗物品即将磨损',
    'Battle item effect timers now display upto 99 hours': '战斗物品效果计时器现在可以显示到99小时。',
    'Battle items no longer always active': '战斗物品不再总是活跃',
    'BattleItems now buy correctly': '现在正确购买战斗物品',
    'before you are able to travel between regions again.': '才能够再次在不同地区之间旅行。',
    'Berries are less likely to create mutations of themselves': '浆果不易产生自身的变异。',
    'Berries are less likely to mutate nearby plots to themselves': '浆果不易使附近的地块向自己突变',
    'Berries can be traded with Berry Masters in later regions for other useful items': '浆果可以在以后的地区与浆果大师交易，换取其他有用的物品。',
    'Berries Harvested': '收获的浆果',
    'Berries have the chance to cause mutations and create new Berry species in empty plots based on certain conditions.': '浆果有机会根据一定的条件在空地上引起变异，并创造出新的浆果品种。',
    'Berries Mutated': '浆果变异',
    'Berries Replanted': '浆果再植',
    'Berry Daily Deal Trades': '浆果每日交易',
    'Berry hints updating correctly each day': '浆果提示每天正确更新',
    'Berry Master': '浆果大师',
    'Berry ready to harvest': '浆果准备收获',
    'Berry Statistics': '浆果统计',
    'Bomb will mine 2 layers of 10 random tiles.': '炸弹会开采2层10块随机瓷砖。',
    'Bonsly on route 209.': '邦斯利在209号公路上。',
    'Boost Dungeon Tokens gained slightly': '提升地下城代币的收益',
    'Breeding display takes up less space on smaller screens now': '养殖展示在小屏幕上占用的空间更小了。',
    'Breeding Efficiency': '繁殖效率',
    'Breeding progress display': '育种进度显示',
    'Bronzor on route 206.': '206路的 铜镜怪。',
    'Buff P2 Lab, increase boss pool': 'Buff P2实验室，增加boss池',
    'Buffed Babiri berry effect': '减弱Babiri浆果效果',
    'Buffed bonus for the Cell Battery': '减弱电池的Buff效果',
    'Buffed Dungeon Token gain in higher regions': '较高地区的地下城令牌收益被弱化了。',
    'Buffed egg steps for baby Pokémon': '减弱宝可梦的孵蛋步骤',
    'Buffed Enigma berry': '减弱Enigma浆果',
    'Buffed Erika Victreebel': '减弱埃里卡大食花',
    'Buffed Farm wondering Pokémon rate': '水牛农场想知道宝可梦率',
    'Buizel on route 205.': '泳圈鼬 在205号公路上。',
    'Burmy (plant': '牛黄(植物',
    'But be aware, if you leave early, You will not earn anything.': '但要注意，如果你提前离开，你将什么也赚不到。',
    'Buttons added to achievement modal to jump to first and last pages': '在成就模式中添加了跳转到第一页和最后一页的按钮。',
    'Can add Pokémon to custom Categories, and sort/filter by those': '可以将宝可梦添加到自定义分类中，并根据这些分类进行排序/过滤。',
    'Can filter Daycare Pokémon by name (regex supported': '可以按名称过滤日托宝可梦（支持正则表达式）。',
    'Can hide the Pokémon filter in the Hatchery': '可以隐藏在孵化器中的宝可梦过滤器。',
    'Can no longer breed fossils from regions you have not reached yet': '不能再从你尚未到达的地区繁殖化石了。',
    'Can no longer evolve Magmar and Electabuzz before you are allowed': '在你被允许之前，不能再进化出 鸭嘴火兽 和 电击兽。',
    'Can no longer move around the Safari Zone before paying': '在支付之前，不能再在狩猎地带周围移动。',
    'Can no longer start a new Pokémon League battle if modal open': '如果模式打开，就不能再开始新的口袋妖怪联盟战斗了',
    'Can no longer upgrade shard effectiveness where there is no usage': '在没有使用的情况下，不能再提升碎片的效能了',
    'Can now filter the Pokédex by pure type Pokémon by selecting None for the second type': '现在可以通过选择第二种类型的"无"来过滤纯类型的宝可梦。',
    'Can now progress in multiple quest at a time': '现在可以同时进行多个任务了',
    'Can now sort Pokémon list by Breeding Efficiency': '现在可以按繁殖效率对宝可梦列表进行排序了。',
    'Can now sort Pokémon list by Egg Steps': '现在可以按蛋步对宝可梦列表进行排序。',
    'Can now use spacebar to start Gym/Dungeon': '现在可以用空格键启动健身房/地下城了',
    'Can obtain Pokémon from future generations by re-breeding': '可以通过重新培育获得后代的宝可梦。',
    'Can see your list of eggs and fossils even if you cannot breed them': '即使不能繁殖，也能看到你的蛋和化石清单。',
    'Can sort Pokémon by Times Hatched': '可以按孵化时间对宝可梦进行分类',
    'Can sort Pokémon list by total proteins used': '可以根据使用的蛋白质总量对宝可梦列表进行排序。',
    'Can sort Underground items by clicking on table titles': '可以通过点击表格标题对地下物品进行排序。',
    'Castform (snowy': '飘浮泡泡(雪)',
    'Categories': '类别',
    'Category': '种类',
    'Category list no longer cut off in Hacthery': '类别列表在Hacthery不再被切断。',
    'Caught Unique Pokemons By Region': '各地区独特的口袋妖怪',
    'Cell Battery Oak Item will now gain points each time you find an item': '橡树电池项目现在每次找到一个项目都会获得积分。',
    'Cerulean': '华蓝',
    'Chatot on route 213.': '查特在213号公路上。',
    'Cherrim (overcast': '樱花儿(阴天形态)',
    'Cherrim (sunshine': '樱花儿(晴天形态)',
    'Chingling on route 211.': '211路的铃铛响。',
    'Chisel will mine two layers on a single tile.': '镐子会在一块瓷砖上开采两层。',
    'claim': '声称',
    'Claw Fossil': '爪子化石',
    'Clear Dungeon': '清理地牢',
    'Clear Gym': '清理道馆',
    'Color': '色彩',
    'Complete Farm overhaul': '农场全面整修',
    'Completed': '已完成',
    'Completed "Capture 382 Pokémon." for 501 quest points.': '完成"捕捉382只宝可梦。"获得501个任务点。',
    'Completed "Catch 1 shiny Pokémon." for 2872 quest points.': '完成了"捕捉1只闪光的宝可梦。"，获得2872点任务积分。',
    'Completed "Defeat 350 Pokémon on Kanto Route 4." for 342 quest points.': '完成了"在关东路线4上击败350只宝可梦"，获得342点任务点数。',
    'Completed "Defeat 354 Pokémon on Johto Route 40." for 327 quest points.': '完成了"在城都路线40上打倒354只宝可梦"，获得327点任务点数。',
    'Completed "Defeat Lavaridge Town gym 10 times." for 697 quest points.': '完成"10次击败拉瓦里奇镇体育馆。"获得697点任务积分。',
    'Completed "Gain 2,719 dungeon tokens." for 276 quest points.': '完成"获得2719个地下城令牌。"获得276个任务点。',
    'Completed "Gain 33,646 PokéDollars." for 56 quest points.': '完成"获得33,646个宝可梦。"获得56个任务点。',
    'Completed "Gain the benefit from the Exp Share 211 times." for 195 quest points.': '完成"从ExpShare中获得好处211次。"获得195点任务积分。',
    'Completed "Hatch 9 Eggs." for 269 quest points.': '完成了"孵化9个蛋。"，获得269点任务积分。',
    'Completed "Use 263 Pokeballs." for 250 quest points.': '完成了"使用263个精灵球。"获得250点任务积分。',
    'Completed Quest and Achievements will show in the Log Book': '已完成的任务和成就将显示在日志中。',
    'A billion Poképennies': '十亿宝可梦',
    'A Small Fortune': '小富即安',
    'A television set that is tuned to a program with useful tips for novice TRAINERS': '一台电视机，调到了一个为新手培训师提供有用提示的节目。',
    'A weaker version of all three effects.': '三个效果的弱化版。',
    'A world of dreams and adventures with Pokémon awaits! Let\'s go': '一个充满梦想和冒险的宝可梦世界在等待着你!走吧',
    'A world of dreams and adventures with Pokémon awaits! Let\'s go!': '充满梦想和冒险的口袋妖怪世界在等着你!出发吧!',
    'Acheivements re-filter once acheivement completed': '成就完成后，重新过滤成就。',
    'Achievement modal pages should now show the correct numbers': '成就模式页面现在应该显示正确的数字。',
    'Add Croagunk to Route': '添加 不良蛙 到路线',
    'Add events modal': '添加事件模式',
    'Add initial Hoenn region': '添加初始丰缘地区',
    'Add Leave button to dungeon entrance': '在地下城入口处添加离开按钮',
    'Add more notification sounds and settings': '添加更多的通知声音和设置',
    'Add notification settings': '添加通知设置',
    'Add option to display Pokédex ID in hatchery': '增加在孵化器中显示图鉴ID的选项。',
    'Add redeemable codes to get a quick boost. You can enter them under the Save tab': '添加可兑换代码以获得快速提升。您可以在"保存"标签下输入',
    'Add setting to disable currency animations': '添加设置以禁用货币动画',
    'Add setting to switch between different growth timers in the Farm': '在农场中增加了在不同生长定时器之间切换的设置。',
    'Add setting to toggle egg percentage/step count': '添加设置以切换蛋百分比/步数。',
    'Add some new game codes': '添加一些新的游戏代码',
    'Add some spacing to Damage Calculator': '在伤害计算器中添加一些间距',
    'Add sparkle to shiny overworld sprites for Dynamic Background and Safari Zone': '为动态背景和狩猎地带的闪光世界精灵添加闪光。',
    'Add tooltips to battle item values': '为战斗项目值添加工具提示',
    'Added a notification for when the game has an update available': '加入了游戏有更新时的通知',
    'Added ability to sell/trade multiple items at once in the Underground': '增加了在地下城中同时出售/交易多个物品的功能。',
    'Added ability to Skip layers in the Underground': '增加了在地下跳过图层的功能',
    'Added ability to track event Pokémon statistics': '增加了跟踪事件宝可梦统计的功能',
    'Added ability to use multiple battle items in 1 click': '增加了一键使用多个战斗物品的功能。',
    'Added Achievement Tracker module': '添加了成就跟踪模块',
    'Added base exp per quest completed': '增加了每完成一个任务的基础指数',
    'Added Bomb ability to the Underground which will mine random tiles for you': '在地下增加了炸弹功能，它将为你随机开采瓷砖。',
    'Added button to open Dock for cities located nearby': '增加了打开附近城市Dock的按钮。',
    'Added caught status indicator to Dungeons': '在地下城中加入了捕获状态指示器',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Lets GO': '出发',
    'Lets go': '出发',
    'Leave Dungeon': '离开地牢',
    'Key Items': '关键物品',
    'Leave': '离开',
    'not': '不',
    'MAXED': '最大',
    'Merry Christmas': '圣诞快乐',
    'MAX LEVEL': '最高级',
    'Locked': '未解锁',
    'Key items': '关键物品',
    'Fossils': '化石',
    'Shinies Encountered': '遇到的闪光宝可梦',
    'Shinies Captured': '孵化的闪光宝可梦',
    'Shinies Hatched': '抓到的闪光宝可梦',
    'Shinies Defeated': '击败的闪光宝可梦',
    'Search': '搜索',
    'Save Data': '存档数据',
    'Removed hold evolution items from the Underground': '从地下移除了保持进化物品',
    'Regional Travel': '区域旅行',
    'Quest is ready to be completed': '任务准备完成',
    'Percentage': '百分比',
    'Old save can be backed up when the game updates incase anything goes wrong': '当游戏更新以防万一出问题时，可以备份旧的存档',
    'Old Quests will no longer give a notification when completed once they are refreshed': '旧任务完成刷新后，将不再发出通知',
    'Oh No! We got ambushed by these pokémon': '不好了！ 我们被这些宝可梦伏击了',
    'NotVery': '不特别',
    'No active quest': '没有进行中的任务',
    'My First Hundo': '我的第一个Hundo',
    'When Pokémon are in a Region they\'re not native to, they will only retain': '当宝可梦不在某个地区时，他们只会保留',
    'Welcome to the Battle Frontier': '欢迎来到前线',
    'What will you do?': '你要做什么?',
    'Volume': '音量',
    'Your safari exploration will end when you have run out of pokeballs.': '当你用完所有的精灵球后，你的探险之旅将会结束。',
    'You\'ll get special items if you reach special milestone stages.': '如果达到特殊的里程碑阶段，您将获得特殊的物品。',
    'Dungeons with a large amount of Pokémon will no longer hide the start button': '携带大量神奇宝贝的地牢将不再隐藏开始按钮',
    'Dungeons should now award Dungeon Tokens when catching a Pokémon': '地牢现在应该在捕获神奇宝贝时奖励地牢代币',
    'Unfortunately, you don\'t have any pokémon of level 100 to breed.': '不幸的是，您没有任何100级的宝可梦可以繁殖。',
    'Unfortunately, you don\'t have any free eggslots.': '不幸的是，您没有空闲的孵蛋插槽。',
    'Caught indicator on eggs showing if you have obtained all the Pokémon available in that egg type': '在精灵蛋上的捕捉指示器，显示你是否获得了该精灵蛋类型的所有可获得的宝可梦',
    'Catch 1 shiny Pokémon.': '抓到1只闪光宝可梦。',
    'Capture 1 Pokémon. When you defeat a Pokémon, a pokeball is thrown and you have a chance to capture it.': '捕获1只宝可梦。 当您击败宝可梦时，抛出一个精灵球，您就有机会抓住它。',
    'Click here to deal "Click Attack" damage to Pokémon.': '单击此处对宝可梦造成“点击攻击”伤害。',
    'Defeat the Pokémon. Click to deal damage': '击败宝可梦。 点击造成伤害',
    'This is where your journey begins.': '这是你旅程的开始。',
    'You will also have to progress to the Dock in': '你也必须进行到码头',
    'To help you on your journey, I will give you these': '为了帮助你的旅途，我将给你这些',
    'Defeat 287 Pokémon on route 13.': '在13号路上打败287只宝可梦。',
    'Defeat the Power Plant dungeon 8 times.': '击败发电厂地牢8次。',
    'Select which information is displayed under each Pokémon in the Daycare': '选择日托中每个神奇宝贝下显示的信息',
    'Previously captured Shiny Pokémon will use this ball selection': '先前捕获的闪光宝可梦将使用此精灵球',
    'Previously captured Pokémon will use this ball selection': '先前捕获的宝可梦将使用此精灵球',
    'Uncaptured Pokémon will use this ball selection': '未捕获的宝可梦将使用此精灵球',
    'Uncaptured Shiny Pokémon will use this ball selection': '未捕获的闪光宝可梦将使用此精灵球',
    'Unlock new plot': '解锁新剧情',
    'Upgrades': '升级',
    'Upgrade': '升级',
    'Use evolution stones': '使用进化石',
    'used for cloud saves,': '用于云存储，',
    'A short set of quests to get you going': '一组简短的任务带你入门',
    ' 10 pokeballs. You can find these in the Viridian City Shop.': '10个精灵球。 您可以在常青市超市找到这些。',
    'Defeat 10 Pokémon on route 2. Click route 2 on the map to move there and begin fighting.': '在路线2上击败10个宝可梦。在地图上点击路线2移至那里并开始战斗。',
    'Town Map will now be fully hidden when it is supposed to be': '',
    'Towns will show as orange if you have not yet completed the gym': '如果您尚未打通健身馆，城镇将显示为橙色',
    'Pokédex filtering should be working again': '图鉴过滤应该可以正常工作了',
    'Hide alternate forms from Pokédex that have not yet been caught': '',
    'Hello, there! Welcome to the world of Pokémon!': '你好！ 欢迎来到宝可梦的世界！',
    'Hm! Excellent! You have caught your first pokémon!': '嗯！ 优秀！ 您已经抓到了您的第一只宝可梦！',
    'Here you will be battling through many stages to earn Battle Points.': '在这里，您将经历许多阶段的战斗，以获得战斗积分。',

    //更新日志
    'FIXED': '修复',
    'Saves should no longer have issues downloading': '存档应该不再有下载问题',
    'Add battle items': '添加战斗物品',
    'Add confirmation when refreshing quest list': '刷新任务列表时添加确认',
    'Achievements can now be filtered': '现在可以过滤成就',
    'Achievements available for all regions': '适用于所有地区的成就',
    'Achievements added for reaching maximum level on oak items': '为达到橡木产品的最高等级而增加的成就',
    'Achievement pages being empty after completing last item on page': '完成页面上的最后一项后，成就页面为空',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
//    原样输出
    'Wiki': 'Wiki',
    'NPC': 'NPC',
    'ⓘ': 'ⓘ',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    'Shiny': '闪光',
    'Shiny ': '闪光',
    'Buy': '购买',
    'Gain': '获得',
    'Use': '使用',
    'The ': '',
    'Total ': '总计',
    'Energy: ': '能量: ',
    'Pokémon ': '宝可梦',
    'Pokemon': '宝可梦',
    'Indigo Plateau': '精灵联盟',
    'Town Map (': '城镇地图(',
    'Travel to ': '前往 ',
    'Quests (': '任务 (',
    'You have captured a ': '您抓到了一只 ',
    'You have captured a': '您抓到了一只 ',
    'You encountered a wild ': '你遇到了一只野生的 ',
    ' You got a ': '你得到一个',
    '[Achievement] ': '[成就] ',
    'Select an achievement to track': '选择要追踪的成就',
    'Ball (': '精灵球 (',
    'Catch Chance': '捕捉几率',
    'Gain the benefit from the Magic Ball': '获得魔法球效果',
    'Obtain ': '获得 ',
    'Oak Items Equipped: ': '已装备高级道具：',
    'Allow the game to continue running while ': '允许游戏继续运行当',
    'I\'ve heard that growing': '我早就听说了',
    'I\'ve heard that a special Berry can appear if its surroundings get too Spicy!': '我听说如果周围的环境太辣，一种特殊的浆果就会出现!',
    'I\'ve heard that a special Berry can appear if its surroundings get too Dry!': '我听说如果周围的环境太干，一种特殊的浆果就会出现!',
    'I\'ve heard that a special Berry can appear if its surroundings get too Sweet!': '我听说如果周围的环境太甜，一种特殊的浆果就会出现!',
    'I\'ve heard that a special Berry can appear if its surroundings get too Bitter!': '我听说如果周围的环境太苦，一种特殊的浆果就会出现!',
    'I\'ve heard that a special Berry can appear if its surroundings get too sour!': '我听说如果周围的环境太酸，一种特殊的浆果就会出现!',
    'I\'ve heard that a special Berry can appear if its surroundings match its flavor profile!': '我听说如果周围的环境和它的味道相匹配，就会出现一种特殊的浆果!',
    'Earned "Johto Route ': '获得“城都地区 路线',
    'Earned "Sinnoh Route ': '获得“神奥地区 路线',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "!": "!",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " region is now available": " 地区已开放",
    ' berry!': '浆果！',
    ' items found': ' 待发现宝物',
    'Eggs.': '蛋。',
    'times.': '次。',
    'diamonds': '钻石',
    'Dungeon Tokens': '地牢令牌',
    'Pokédollars': '宝可币',
    'PokéDollars.': '宝可币。',
    'Pokémon.': '宝可梦。',
    'berries at the farm.': '浆果，从农场里。',
    'until grown': '后长大',
    'until Bloom': '后开花',
    'until ripe': '后成熟',
    'until death': '后死亡',
    'Berries neareach other will produce something interesting!': '相互靠近会产生一些有趣的东西',
    'If I recall, it tasted a little spicy, a little sweet, and a little sour at the same time!': '我没记错的话，它的味道同时有 辣，甜，酸!',
    'If I recall, it tasted fairly spicy, dry, and bitter at the same time': '我没记错的话，它的味道同时有 辣，干，苦',
    'bug shards': '虫碎片',
    'dark shards': '暗碎片',
    'dragon shards': '龙碎片',
    'fighting shards': '格斗碎片',
    'fire shards': '火碎片',
    'flying shards': '飞行碎片',
    'ghost shards': '幽灵碎片',
    'grass shards': '草碎片',
    'ground shards': '地碎片',
    'ice shards': '冰碎片',
    'poison shards': '毒碎片',
    'psychic shards': '物理碎片',
    'rock shards': '石碎片',
    'water shards': '水碎片',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.,]+) \/$/, '$1 \/'],
    [/^You will now start the game with (.+) Pokéballs$/, '现在你将以 $1 个 精灵球 开始游戏'],
    [/^Attack: (\d+),$/, '攻击：$1，'],
    [/^(\d+) traveler".$/, '$1 次旅行者”。'],
    [/^(\d+) explorer".$/, '$1 次探险者”。'],
    [/^(\d+) secs$/, '$1 秒'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);